### ISSUE TITLE
rdflib.plugin.PluginException problem

### ISSUE THREAD

**Issue by adhollander** [linkml/linkml#1019]
When trying to run linkml-validate on a turtle file, I consistently get the following error message:
`rdflib.plugin.PluginException: No plugin registered for (rdf, <class 'rdflib.parser.Parser'>)`

The full error listing is as follows:
```
$ linkml-validate -f ttl -s PPOD.yaml ../PPOD0.ttl
Traceback (most recent call last):
  File "/media/adh/Elements/WorkFromHome/ASI/ConservationOntology/CaPPOD/PPODLinkML/lib/python3.8/site-packages/rdflib/plugin.py", line 127, in get
    p: Plugin[PluginT] = _plugins[(name, kind)]
KeyError: ('rdf', <class 'rdflib.parser.Parser'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/adh/Elements/WorkFromHome/ASI/ConservationOntology/CaPPOD/PPODLinkML/bin/linkml-validate", line 8, in <module>
    sys.exit(cli())
  File "/media/adh/Elements/WorkFromHome/ASI/ConservationOntology/CaPPOD/PPODLinkML/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/media/adh/Elements/WorkFromHome/ASI/ConservationOntology/CaPPOD/PPODLinkML/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/media/adh/Elements/WorkFromHome/ASI/ConservationOntology/CaPPOD/PPODLinkML/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/media/adh/Elements/WorkFromHome/ASI/ConservationOntology/CaPPOD/PPODLinkML/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/media/adh/Elements/WorkFromHome/ASI/ConservationOntology/CaPPOD/PPODLinkML/lib/python3.8/site-packages/linkml/validators/jsonschemavalidator.py", line 114, in cli
    obj = loader.load(source=input, target_class=py_target_class, **inargs)
  File "/media/adh/Elements/WorkFromHome/ASI/ConservationOntology/CaPPOD/PPODLinkML/lib/python3.8/site-packages/linkml_runtime/loaders/rdflib_loader.py", line 239, in load
    g.parse(source, format=fmt)
  File "/media/adh/Elements/WorkFromHome/ASI/ConservationOntology/CaPPOD/PPODLinkML/lib/python3.8/site-packages/rdflib/graph.py", line 1327, in parse
    parser = plugin.get(format, Parser)()
  File "/media/adh/Elements/WorkFromHome/ASI/ConservationOntology/CaPPOD/PPODLinkML/lib/python3.8/site-packages/rdflib/plugin.py", line 129, in get
    raise PluginException("No plugin registered for (%s, %s)" % (name, kind))
rdflib.plugin.PluginException: No plugin registered for (rdf, <class 'rdflib.parser.Parser'>)

```
I also get a similar error when trying to run linkml-sqldump on the same turtle file.  This is occurring under rdflib 6.2.0 and linkml 1.3.8, and I've replicated it in two new python environments, one in linux mint using python 3.8, and one in Windows 10 using python 3.9.

The relevant files for this problem are:

PPOD0.ttl, available at https://raw.githubusercontent.com/adhollander/PPODtottl/main/PPOD0.ttl, 
PPOD.yaml, at https://raw.githubusercontent.com/adhollander/PPODLinkML/main/PPOD.yaml,
vocabs.yaml, at https://raw.githubusercontent.com/adhollander/PPODLinkML/main/vocabs.yaml

**Comment by cmungall** [comment]
Confirmed, I get the same as you. Also for linkml-convert. For some reason the format is being passed to rdflib as `rdf` when it should be `turtle`.

I'm not sure what changed and how this passed through our tests, but it should be a quick fix.

Once this is resolved you will have an issue with the any_ofs - as you note this is new in linkml 1.3 and it may not be fully supported.
