### ISSUE TITLE
`ValueError: SchemaDefinition.id must be supplied` encountered while following Part 8: Generating Projects

### ISSUE THREAD

**Issue by capsulecorplab** [linkml/linkml#1030]
**Describe the bug**
Encountered following ValueError while following [Part 8: Generating Projects](https://linkml.io/linkml/intro/tutorial08.html#part-8-generating-projects)

```
$ gen-project -d personinfo/ personinfo.yaml 
ALL_SCHEMAS = ['personinfo.yaml']
INFO:root:Generating: graphql
INFO:root: SCHEMA: personinfo.yaml
INFO:root: PARENT=personinfo//graphql
Traceback (most recent call last):
  File "/usr/local/bin/gen-project", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/linkml/generators/projectgen.py", line 258, in cli
    gen.generate(yamlfile, project_config)
  File "/usr/local/lib/python3.8/dist-packages/linkml/generators/projectgen.py", line 148, in generate
    gen = gen_cls(local_path, **all_gen_args)
  File "<string>", line 22, in __init__
  File "/usr/local/lib/python3.8/dist-packages/linkml/generators/graphqlgen.py", line 25, in __post_init__
    super().__post_init__()
  File "/usr/local/lib/python3.8/dist-packages/linkml/utils/generator.py", line 189, in __post_init__
    self._initialize_using_schemaloader(schema)
  File "/usr/local/lib/python3.8/dist-packages/linkml/utils/generator.py", line 220, in _initialize_using_schemaloader
    loader = SchemaLoader(
  File "/usr/local/lib/python3.8/dist-packages/linkml/utils/schemaloader.py", line 65, in __init__
    self.schema = load_raw_schema(
  File "/usr/local/lib/python3.8/dist-packages/linkml/utils/rawloader.py", line 77, in load_raw_schema
    schema = yaml_loader.load(
  File "/usr/local/lib/python3.8/dist-packages/linkml_runtime/loaders/loader_root.py", line 85, in load
    results = self.load_any(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/linkml_runtime/loaders/yaml_loader.py", line 25, in load_any
    return self.load_source(source, loader, target_class, accept_header="text/yaml, application/yaml;q=0.9",
  File "/usr/local/lib/python3.8/dist-packages/linkml_runtime/loaders/loader_root.py", line 66, in load_source
    return target_class(**data_as_dict)
  File "<string>", line 58, in __init__
  File "/usr/local/lib/python3.8/dist-packages/linkml_runtime/linkml_model/meta.py", line 459, in __post_init__
    self.MissingRequiredField("id")
  File "/usr/local/lib/python3.8/dist-packages/linkml/utils/rawloader.py", line 27, in mrf
    YAMLRoot.MissingRequiredField(self, f"{type(self).__name__}.{field_name}")
  File "/usr/local/lib/python3.8/dist-packages/linkml_runtime/utils/yamlutils.py", line 250, in MissingRequiredField
    raise ValueError(f"{field_name} must be supplied")
ValueError: SchemaDefinition.id must be supplied
```

**To Reproduce**
1. create `personinfo.yaml` as per [Part 8: Generating Projects](https://linkml.io/linkml/intro/tutorial08.html#part-8-generating-projects)
2. run `gen-project -d personinfo/ personinfo.yaml `

**Expected behavior**
Should generate artifacts in the `personinfo/` directory

**Screenshots**
![Screenshot from 2022-10-22 15-14-24](https://user-images.githubusercontent.com/14095576/197362702-1674e035-74ce-4f3f-828d-cde170dea536.png)

**Desktop (if applicable, please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by capsulecorplab** [comment]
closing issue, was a typo in the schema
