### ISSUE TITLE
linkml-validate should not issue a stack trace

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#1039]
Using the [example in the LinkML Tutorial] we get the following:
```
> linkml-validate -s personinfo.yaml bad-data.yaml
Traceback (most recent call last):
  File "/Users/solbrig/Development/linkml-tutorial/venv/bin/linkml-validate", line 8, in <module>
    sys.exit(cli())
  File "/Users/solbrig/Development/linkml-tutorial/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/solbrig/Development/linkml-tutorial/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/solbrig/Development/linkml-tutorial/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/solbrig/Development/linkml-tutorial/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/solbrig/Development/linkml-tutorial/venv/lib/python3.10/site-packages/linkml/validators/jsonschemavalidator.py", line 141, in cli
    obj = loader.load(source=input, target_class=py_target_class, **inargs)
  File "/Users/solbrig/Development/linkml-tutorial/venv/lib/python3.10/site-packages/linkml_runtime/loaders/loader_root.py", line 85, in load
    results = self.load_any(*args, **kwargs)
  File "/Users/solbrig/Development/linkml-tutorial/venv/lib/python3.10/site-packages/linkml_runtime/loaders/yaml_loader.py", line 25, in load_any
    return self.load_source(source, loader, target_class, accept_header="text/yaml, application/yaml;q=0.9",
  File "/Users/solbrig/Development/linkml-tutorial/venv/lib/python3.10/site-packages/linkml_runtime/loaders/loader_root.py", line 66, in load_source
    return target_class(**data_as_dict)
  File "<string>", line 8, in __init__
  File "test", line 75, in __post_init__
  File "/Users/solbrig/Development/linkml-tutorial/venv/lib/python3.10/site-packages/linkml_runtime/utils/yamlutils.py", line 48, in __post_init__
    raise ValueError('\n'.join(messages))
ValueError: File "<file>", line 5, col 1:  Unknown argument: made_up_field = 'hello'
>
```

This should JUST have the last line.

The following patch to `yamlutils.py`  could fix this particular example:
```
            # raise ValueError('\n'.join(messages))
            print("\n".join(messages), file=sys.stderr)
            sys.exit(1)
```
but, in general, we probably want to just catch `ValueError` and other(?) messages and do the above.  Note that:
1) `yamlutils.py` is used by a _lot_ of functions
2) there are a lot of different messages being thrown

**Comment by cmungall** [comment]
See also

- #892

This should also be subsumed by:

- #368.          

As we should not be using exceptions to communicate validation errors at all. We should return validation objects

**Comment by nlharris** [comment]
Related to #101?

**Comment by sierra-moxon** [comment]
closeable! :)
