### ISSUE TITLE
Using reserved words such as 'null' generates undecipherable stack traces

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#104]
if I use the keyword `null` as a slot name:

```yaml
id: http://w3id.org/test
description: test
imports:
- biolinkml:types
prefixes:
  biolinkml: https://w3id.org/biolink/biolinkml/
  test: https://w3id.org/mixs/
default_prefix: test
slots:
  null: {}
  
classes:
  core:
    slots:
    - null
```

and try and use any generator I get stack traces that don't identify the root cause. this can be hard to debug in large schemas

```bash
$ gen-py-classes ~/tmp/bad.yaml 
/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/__init__.py:158: UserWarning: Some URL processing will fail with python 3.7.5 or earlier.  Current version: sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
  warn(f"Some URL processing will fail with python 3.7.5 or earlier.  Current version: {sys.version_info}")
Traceback (most recent call last):
  File "/Users/cjm/repos/mixs-demo/venv/bin/gen-py-classes", line 11, in <module>
    sys.exit(cli())
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/generators/pythongen.py", line 881, in cli
    print(PythonGenerator(yamlfile, emit_metadata=head, gen_meta=genmeta, gen_classvars=classvars, gen_slots=slots,  **args).serialize(emit_metadata=head, **args))
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/generators/pythongen.py", line 35, in __init__
    super().__init__(schema, format, **kwargs)
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/utils/generator.py", line 91, in __init__
    source_file_date=self.source_file_date, source_file_size=self.source_file_size)
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/utils/schemaloader.py", line 52, in __init__
    source_file_size=source_file_size)
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/utils/rawloader.py", line 78, in load_raw_schema
    emit_metadata=emit_metadata)
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/utils/rawloader.py", line 150, in load_raw_schema
    for sname, sdef in {k: SchemaDefinition(name=k, **v) for k, v in schemadefs.items()}.items():
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/utils/rawloader.py", line 150, in <dictcomp>
    for sname, sdef in {k: SchemaDefinition(name=k, **v) for k, v in schemadefs.items()}.items():
  File "<string>", line 48, in __init__
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/meta.py", line 390, in __post_init__
    self._normalize_inlined_slot(slot_name="slots", slot_type=SlotDefinition, key_name="name", inlined_as_list=None, keyed=True)
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/utils/yamlutils.py", line 129, in _normalize_inlined_slot
    cook_a_slot(slot_type(**value_copy))
  File "<string>", line 66, in __init__
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/meta.py", line 641, in __post_init__
    raise ValueError("name must be supplied")
ValueError: name must be supplied
```

**Comment by cmungall** [comment]
Another example: dosdp schema uses a slot name `in` which is reserved in python

**Comment by gaurav** [comment]
One possible fix would be to add a prefix (such as `slot_`) to any slot name that is a Python keyword or is not a valid Python identifer. This can be determined by using [`str.isidentifier`](https://docs.python.org/3/library/stdtypes.html?highlight=identifier#str.isidentifier) to check if a string is a valid identifier in Python, and [`keyword.iskeyword`](https://docs.python.org/3/library/keyword.html#keyword.iskeyword) to check if it a string is a keyword in the currently running Python interpreter.

**Comment by kevinschaper** [comment]
I just hit this while working on javagen today, the alliance schema has an `abstract` slot on References. In this case, I can imagine that I might want to generate a Java property called `abstractText` more than `slot_abstract` 

Is it over engineering to have a default renaming scheme and also the ability to override it with a command line argument?

**Comment by cmungall** [comment]
I think we need the renaming scheme, but in the interim we should just give friendly warnings/errors.

For the renaming we need to make sure things are coordinated, as often framework X needs to communicate with framework Y. E.g. the pythongen classes are automatigically made from JSON objects, relying on keys matching fields. For e.g. python to SQL there is a more explicit mapping with sqla bindings. 

good tip @gaurav I wasn't aware of those methods

Let's discuss on friday call

**Comment by kevinschaper** [comment]
Here's that reserved word collection repo that I mentioned Friday: https://github.com/AnanthaRajuC/Reserved-Key-Words-list-of-various-programming-languages/tree/master/language-files, it's a shame that it's not meant to be machine readable. Maybe keeping anything in the markdown that's part of a list but isn't a single letter?

**Comment by adlerfaulkner** [comment]
I have another example of this when trying to use `slot_uri: rr:class` (from the [rml ontology](https://rml.io/)).
I get this error when running `linkml-convert`
```
(venv) Adlers-MacBook-Pro-2:skl-model adlerfaulkner$ linkml-convert -o data.ttl -s linkml-model.yaml data.yaml
Traceback (most recent call last):
  File "/Users/adlerfaulkner/skl/packages/skl-model/venv/bin/linkml-convert", line 8, in <module>
    sys.exit(cli())
  File "/Users/adlerfaulkner/skl/packages/skl-model/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/adlerfaulkner/skl/packages/skl-model/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/adlerfaulkner/skl/packages/skl-model/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/adlerfaulkner/skl/packages/skl-model/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/adlerfaulkner/skl/packages/skl-model/venv/lib/python3.9/site-packages/linkml/utils/converter.py", line 72, in cli
    python_module = PythonGenerator(schema).compile_module()
  File "/Users/adlerfaulkner/skl/packages/skl-model/venv/lib/python3.9/site-packages/linkml/generators/pythongen.py", line 56, in compile_module
    return compile_python(pycode)
  File "/Users/adlerfaulkner/skl/packages/skl-model/venv/lib/python3.9/site-packages/linkml_runtime/utils/compile_python.py", line 30, in compile_python
    spec = compile(python_txt, 'test', 'exec')
  File "test", line 1092
    slots.rrclass = Slot(uri=RR.class, name="rrclass", curie=RR.curie('class'),
                                ^
SyntaxError: invalid syntax
```

**Comment by nlharris** [comment]
See also #101, "Stack dump doesn't belong in value errror messages".

**Comment by dalito** [comment]
@sierra-moxon This is the oldest dev-days issue. 

The failing examples given above work fine now. I tested with linkML 1.8.5. So this could probably be closed. 

 Done?! 😄

**Comment by sierra-moxon** [comment]
@dalito - the best kind of ticket!! :D pls do close as needed.

**Comment by dalito** [comment]
I could not reproduce this with any of the examples above. 
Please reopen if you have an example that fails with a current version of linkML.
