### ISSUE TITLE
gen-yuml fails in LinkML example

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#1045]
When I follow [Example 2](https://linkml.io/linkml/intro/tutorial02.html#) in the linkml tutorial, I get the following:
```
> gen-yuml -f yuml personinfo.yaml 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/gen-yuml", line 11, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/metamodel/generators/yumlgen.py", line 221, in cli
    print(YumlGenerator(yamlfile, format).serialize(classes=classes, directory=directory), end="")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/metamodel/generators/yumlgen.py", line 41, in __init__
    super().__init__(schema, fmt)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/metamodel/utils/generator.py", line 29, in __init__
    self.schema = schema if isinstance(schema, SchemaDefinition) else SchemaLoader(schema).resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/metamodel/utils/schemaloader.py", line 13, in __init__
    self.schema = load_raw_schema(data, base_dir=base_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/metamodel/utils/loadschema.py", line 40, in load_raw_schema
    return load_raw_schema(f, data, time.ctime(os.path.getmtime(fname)), os.path.getsize(fname))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/metamodel/utils/loadschema.py", line 51, in load_raw_schema
    for sname, sdef in {k: SchemaDefinition(name=k, **v) for k, v in schemadefs.items()}.items():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/metamodel/utils/loadschema.py", line 51, in <dictcomp>
    for sname, sdef in {k: SchemaDefinition(name=k, **v) for k, v in schemadefs.items()}.items():
TypeError: __init__() got an unexpected keyword argument 'default_range'
```

**Comment by cmungall** [comment]
should we change this to use mermaid?

**Comment by hsolbrig** [comment]
I have absolutely no idea what mermaid is.  This turns out to be some sort off terminal issue -- despite the fact that I've got:

`PATH=/Users/solbrig/Development/linkml-tutorial/venv/bin:/Library...`

`which gen-yuml` says `/Library/Frameworks/Python.framework/Versions/3.7/bin/gen-yuml`, which is undoubtedly very old.
