### ISSUE TITLE
Need to incorporate a github id into the unit tests for test_linkml_files

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#1078]
Github limits the number of accesses via the API to 60 per hour if you don't have credentials.

We need to figure out how to fix this for testing.

**Comment by sierra-moxon** [comment]
@hrshdhgd - do you have any suggestions for this ticket?  I can chat briefly if you need more info :)

**Comment by sierra-moxon** [comment]
here's an example:
```
ERROR: test_shorthand_paths (tests.test_linkml_files.LinkMLFilesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/linkml-model/linkml-model/tests/test_linkml_files.py", line 60, in test_shorthand_paths
    self.assertEqual('https://raw.githubusercontent.com/linkml/linkml-model/f30637f5a585f3fc4b12fd3dbb3e7e95108d4b42/model/schema/meta.yaml', str(fileloc.meta.yaml.github_loc('v0.0.1')))
  File "/home/runner/work/linkml-model/linkml-model/linkml_model/linkml_files.py", line 161, in github_loc
    return GITHUB_PATH_FOR(self._model, self._format, tag, branch or "main")
  File "/home/runner/work/linkml-model/linkml-model/linkml_model/linkml_files.py", line 1[34](https://github.com/linkml/linkml-model/actions/runs/3753208713/jobs/6376241836#step:8:35), in GITHUB_PATH_FOR
    return tag_to_commit(release)
  File "/home/runner/work/linkml-model/linkml-model/linkml_model/linkml_files.py", line 114, in tag_to_commit
    tags = do_request(f"{GITHUB_API_BASE}tags")
  File "/home/runner/work/linkml-model/linkml-model/linkml_model/linkml_files.py", line 111, in do_request
    raise requests.HTTPError(f"{resp.status_code} - {resp.reason}: {url}")
requests.exceptions.HTTPError: [40](https://github.com/linkml/linkml-model/actions/runs/3753208713/jobs/6376241836#step:8:41)3 - rate limit exceeded: https://api.github.com/repos/linkml/linkml-model/tags
```
[job output](https://github.com/linkml/linkml-model/actions/runs/3753208713/jobs/6376241836)

**Comment by hrshdhgd** [comment]
[This may be the answer](https://developer.github.com/changes/2012-10-14-rate-limit-changes/) to the problem. I think using a GitHub token to authenticate may solve the issue. I tried to test it but apparently I do not have adequate permissions to enter a GitHub secret in this repository.

**Comment by hrshdhgd** [comment]
I see there already exists a `secrets.CODECOV_TOKEN` to authenticate code coverage. Is there a secret with that variable name in secrets?

**Comment by dalito** [comment]
This does not seem to be an issue anymore. Feel free to re-open.
