### ISSUE TITLE
show line number when reporting errors with multivalued slot

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#115]
```yaml
id: test
prefixes:
  test: https://example.org/
  biolinkml: https://w3id.org/biolink/biolinkml/
  
default_range: string
default_prefix: test

imports:
  - biolinkml:types

slots:
  x:
    multivalued: 2
```

generates:

```bash
Traceback (most recent call last):
  File "/Users/cjm/repos/chemistry-ontology/venv/bin/gen-json-schema", line 11, in <module>
    sys.exit(cli())
  File "/Users/cjm/repos/chemistry-ontology/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cjm/repos/chemistry-ontology/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/cjm/repos/chemistry-ontology/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cjm/repos/chemistry-ontology/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/cjm/repos/chemistry-ontology/venv/lib/python3.7/site-packages/biolinkml/generators/jsonschemagen.py", line 116, in cli
    print(JsonSchemaGenerator(yamlfile, **kwargs).serialize(**kwargs))
  File "/Users/cjm/repos/chemistry-ontology/venv/lib/python3.7/site-packages/biolinkml/generators/jsonschemagen.py", line 19, in __init__
    super().__init__(schema, **kwargs)
  File "/Users/cjm/repos/chemistry-ontology/venv/lib/python3.7/site-packages/biolinkml/utils/generator.py", line 91, in __init__
    source_file_date=self.source_file_date, source_file_size=self.source_file_size)
  File "/Users/cjm/repos/chemistry-ontology/venv/lib/python3.7/site-packages/biolinkml/utils/schemaloader.py", line 52, in __init__
    source_file_size=source_file_size)
  File "/Users/cjm/repos/chemistry-ontology/venv/lib/python3.7/site-packages/biolinkml/utils/rawloader.py", line 78, in load_raw_schema
    emit_metadata=emit_metadata)
  File "/Users/cjm/repos/chemistry-ontology/venv/lib/python3.7/site-packages/biolinkml/utils/rawloader.py", line 150, in load_raw_schema
    for sname, sdef in {k: SchemaDefinition(name=k, **v) for k, v in schemadefs.items()}.items():
  File "/Users/cjm/repos/chemistry-ontology/venv/lib/python3.7/site-packages/biolinkml/utils/rawloader.py", line 150, in <dictcomp>
    for sname, sdef in {k: SchemaDefinition(name=k, **v) for k, v in schemadefs.items()}.items():
  File "<string>", line 48, in __init__
  File "/Users/cjm/repos/chemistry-ontology/venv/lib/python3.7/site-packages/biolinkml/meta.py", line 390, in __post_init__
    self._normalize_inlined_slot(slot_name="slots", slot_type=SlotDefinition, key_name="name", inlined_as_list=None, keyed=True)
  File "/Users/cjm/repos/chemistry-ontology/venv/lib/python3.7/site-packages/biolinkml/utils/yamlutils.py", line 129, in _normalize_inlined_slot
    cook_a_slot(slot_type(**value_copy))
  File "<string>", line 66, in __init__
  File "/Users/cjm/repos/chemistry-ontology/venv/lib/python3.7/site-packages/biolinkml/meta.py", line 658, in __post_init__
    self.multivalued = Bool(self.multivalued)
  File "/Users/cjm/repos/chemistry-ontology/venv/lib/python3.7/site-packages/biolinkml/utils/metamodelcore.py", line 199, in __new__
    raise ValueError(f"{v}: Must be a boolean value")
ValueError: 2: Must be a boolean value
```

with large schemas, it can be hard to track down these issues

**Comment by sujaypatil96** [comment]
Unclear on how to move forward on a resolution for this issue. Need more direction (and preferably more context too).
