### ISSUE TITLE
linkml-sqldb dump -> "Incompatible collection type: dict is not list-like"

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1154]
My model contained some classes with `inlined` slots. when I changed them to `linlined_as_list`, the "Incompatible collection type: dict is not list-like" message went away.

But a new new error appeared:
- [ ] #1160

**Comment by turbomam** [comment]
```
linkml-sqldb dump \
	--db assets/test_data.db \
	--target-class DataListCollection \
	--schema src/cleanroom_schema/schema/cleanroom_schema.yaml assets/test_data.json
WARNING:root:There is no established path to cleanroom-schema - compile_python may or may not work
Traceback (most recent call last):
  File "/home/mark/.local/bin/linkml-sqldb", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mark/.local/lib/python3.8/site-packages/linkml/utils/sqlutils.py", line 336, in dump
    endpoint.dump(obj)
  File "/home/mark/.local/lib/python3.8/site-packages/linkml/utils/sqlutils.py", line 142, in dump
    nu_obj = self.to_sqla(element)
  File "/home/mark/.local/lib/python3.8/site-packages/linkml/utils/sqlutils.py", line 196, in to_sqla
    nu_obj = nu_typ(**inst_args)
  File "<string>", line 4, in __init__
  File "/home/mark/.local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 480, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/home/mark/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/mark/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/mark/.local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 477, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/home/mark/.local/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 1157, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "/home/mark/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 459, in __set__
    self.impl.set(
  File "/home/mark/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 1563, in set
    raise TypeError(
TypeError: Incompatible collection type: dict is not list-like
```
