### ISSUE TITLE
pyydanticgen: the following field constraints are set but not enforced: ge, le

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1167]
```yaml
classes:
  Biosamples:
    slots:
      - dna_concentration
      - ...
      
slots:
  dna_concentration:
    name: dna_concentration
    title: DNA concentration in ng/ul
    comments:
    - Units must be in ng/uL. Enter the numerical part only. Must be calculated using
      a fluorometric method. Acceptable values are 0-2000.
    examples:
    - value: '100'
    from_schema: https://example.com/nmdc_dh
    rank: 5
    string_serialization: '{float}'
    slot_group: JGI-Metagenomics
    required: false
    recommended: true
    minimum_value: 0
    maximum_value: 2000
```

gives:

```python
class Biosample(MaterialEntity):
  ..
  dna_concentration: Optional[str] = Field(None, title="DNA concentration in ng/ul", ge=0, le=2000)
```

which gives:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cjm/repos/nmdc-schema/z.py", line 1992, in <module>
    class Biosample(MaterialEntity):
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 504, in pydantic.fields.ModelField.infer
  File "pydantic/schema.py", line 1011, in pydantic.schema.get_annotation_from_field_info
ValueError: On field "dna_concentration" the following field constraints are set but not enforced: le, ge.
For more details see https://pydantic-docs.helpmanual.io/usage/schema/#unenforced-field-constraints
```

**Comment by cmungall** [comment]
related:

- https://github.com/pydantic/pydantic/issues/2581

**Comment by kevinschaper** [comment]
It looks like the linked pydantic issue is fixed with V2, but even using V2, it doesn't work to set min and max numerical values for a string field. Maybe there's extra context that the default range for this schema is a numerical type - but if that's the case, I guess the bug would be that the range for the field is [str]?

**Comment by cmungall** [comment]
yes it looks like a bug in the schema not linkml
