### ISSUE TITLE
Linkml changes between 1.3.10 and 1.3.12 gives error on schema and data

### ISSUE THREAD

**Issue by samwalrus** [linkml/linkml#1266]
**Describe the bug**
I have written a schema and a data file which validates and can be transformed into rdf using linkml version:

[tool.poetry.dev-dependencies]
linkml = "1.3.10"

But if I use a later version (note poetry was unable to install 1.3.11): 
[tool.poetry.dev-dependencies]
linkml = "1.3.12"

It does not work and I get an error about uriorcurie.

**To reproduce**
1. Go to 'https://github.com/alspac/alspac-data-catalogue-schema'
Using examples:

https://github.com/alspac/alspac-data-catalogue-schema/blob/main/examples/cnv_550_g1/cnv_550_g1_2015-11-09_f2.yaml

And schema:

https://github.com/alspac/alspac-data-catalogue-schema/blob/main/src/alspac_data_catalogue_schema/schema/alspac_data_catalogue_schema.yaml

Run 

`poetry run linkml-validate -s alspac_data_catalogue_schema.yaml cnv_550_g1_2015-11-09_f2.yaml --target-class AlspacDataSetVersionFreeze `

output is:
`none.`

But if you remove the poerty lock file and change the https://github.com/alspac/alspac-data-catalogue-schema/blob/main/pyproject.toml file on line 21 to :  `linkml = "1.3.12"`

Then run `poetry install`

And then

`poetry run linkml-validate -s alspac_data_catalogue_schema.yaml cnv_550_g1_2015-11-09_f2.yaml --target-class AlspacDataSetVersionFreeze `

output:
```
Traceback (most recent call last):
  File "/Users/sn0550/Library/Caches/pypoetry/virtualenvs/alspac-data-catalogue-schema-AmLaKyAp-py3.11/bin/linkml-validate", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/sn0550/Library/Caches/pypoetry/virtualenvs/alspac-data-catalogue-schema-AmLaKyAp-py3.11/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sn0550/Library/Caches/pypoetry/virtualenvs/alspac-data-catalogue-schema-AmLaKyAp-py3.11/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/sn0550/Library/Caches/pypoetry/virtualenvs/alspac-data-catalogue-schema-AmLaKyAp-py3.11/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sn0550/Library/Caches/pypoetry/virtualenvs/alspac-data-catalogue-schema-AmLaKyAp-py3.11/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sn0550/Library/Caches/pypoetry/virtualenvs/alspac-data-catalogue-schema-AmLaKyAp-py3.11/lib/python3.11/site-packages/linkml/validators/jsonschemavalidator.py", line 150, in cli
    results = validator.validate_object(obj, target_class=py_target_class)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sn0550/Library/Caches/pypoetry/virtualenvs/alspac-data-catalogue-schema-AmLaKyAp-py3.11/lib/python3.11/site-packages/linkml/validators/jsonschemavalidator.py", line 49, in validate_object
    ).serialize(not_closed=not_closed)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sn0550/Library/Caches/pypoetry/virtualenvs/alspac-data-catalogue-schema-AmLaKyAp-py3.11/lib/python3.11/site-packages/linkml/generators/jsonschemagen.py", line 310, in serialize
    self.visit_class(class_definition)
  File "/Users/sn0550/Library/Caches/pypoetry/virtualenvs/alspac-data-catalogue-schema-AmLaKyAp-py3.11/lib/python3.11/site-packages/linkml/generators/jsonschemagen.py", line 183, in visit_class
    self.visit_class_slot(
  File "/Users/sn0550/Library/Caches/pypoetry/virtualenvs/alspac-data-catalogue-schema-AmLaKyAp-py3.11/lib/python3.11/site-packages/linkml/generators/jsonschemagen.py", line 245, in visit_class_slot
    range_id_slot = self.schemaview.get_identifier_slot(slot.range, use_key=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sn0550/Library/Caches/pypoetry/virtualenvs/alspac-data-catalogue-schema-AmLaKyAp-py3.11/lib/python3.11/site-packages/linkml_runtime/utils/schemaview.py", line 1195, in get_identifier_slot
    for sn in self.class_slots(cn, imports=imports):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sn0550/Library/Caches/pypoetry/virtualenvs/alspac-data-catalogue-schema-AmLaKyAp-py3.11/lib/python3.11/site-packages/linkml_runtime/utils/schemaview.py", line 1014, in class_slots
    ancs = self.class_ancestors(class_name, imports=imports)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sn0550/Library/Caches/pypoetry/virtualenvs/alspac-data-catalogue-schema-AmLaKyAp-py3.11/lib/python3.11/site-packages/linkml_runtime/utils/schemaview.py", line 609, in class_ancestors
    return _closure(lambda x: self.class_parents(x, imports=imports, mixins=mixins, is_a=is_a),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sn0550/Library/Caches/pypoetry/virtualenvs/alspac-data-catalogue-schema-AmLaKyAp-py3.11/lib/python3.11/site-packages/linkml_runtime/utils/schemaview.py", line 54, in _closure
    vals = f(i)
           ^^^^
  File "/Users/sn0550/Library/Caches/pypoetry/virtualenvs/alspac-data-catalogue-schema-AmLaKyAp-py3.11/lib/python3.11/site-packages/linkml_runtime/utils/schemaview.py", line 609, in <lambda>
    return _closure(lambda x: self.class_parents(x, imports=imports, mixins=mixins, is_a=is_a),
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sn0550/Library/Caches/pypoetry/virtualenvs/alspac-data-catalogue-schema-AmLaKyAp-py3.11/lib/python3.11/site-packages/linkml_runtime/utils/schemaview.py", line 531, in class_parents
    cls = self.get_class(class_name, imports, strict=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sn0550/Library/Caches/pypoetry/virtualenvs/alspac-data-catalogue-schema-AmLaKyAp-py3.11/lib/python3.11/site-packages/linkml_runtime/utils/schemaview.py", line 448, in get_class
    raise ValueError(f'No such class as "{class_name}"')
ValueError: No such class as "uriorcurie"
```
I get a similar error for later versions of linkml.

**Expected behavior**
Output none or some info on why my schema and data are not as they should be.

**About your computer (if applicable, please complete the following information):**
 - OS:Macos
 

**Additional context**
A discussion on Slack with Mark Miler

**Comment by turbomam** [comment]
I was able to validate @samwalrus's `cnv_550_g1_2015-11-09_f2.yaml` datafile against his schema under linkml                        1.4.2 after commenting out several of his `inlined` and `inlined_as_list` assertions.

Note that I added `.txt` extensions to these files so that I could attach them.

[cnv_550_g1_2015-11-09_f2.yaml.txt](https://github.com/linkml/linkml/files/10500218/cnv_550_g1_2015-11-09_f2.yaml.txt)

[alspac_data_catalogue_schema_min_inlining.yaml.txt](https://github.com/linkml/linkml/files/10500235/alspac_data_catalogue_schema_min_inlining.yaml.txt)

**Comment by cmungall** [comment]
This is actually due to an error in the schema, see #240 for an explanation.

@pkalita-lbl fixed the jsonschema generator to be more tolerant, 
Fixed in https://github.com/linkml/linkml-runtime/releases/tag/v1.4.3

thanks all!

**Comment by pkalita-lbl** [comment]
Just to clarify, see https://github.com/linkml/linkml-runtime/pull/240 for the explanation.

The quick summary is: you don't need -- in fact best not to have -- `inlined` or `inlined_as_list` on any slot where the range is a type instead of a class in your schema. In your specific case @samwalrus removing `inlined_as_list` on the `see_also` slot should get you going again.

**Comment by samwalrus** [comment]
Thanks for your help in resolving this.
