### ISSUE TITLE
AttributeError with linkml-validate

### ISSUE THREAD

**Issue by adhollander** [linkml/linkml#1280]
I am trying to develop a data conversion pipeline and I have run into an issue when testing linkml-validate on my data. This has come about when I've been learning to work with Containers.  Here is a test case. When I make the call `linkml-validate -C Container  -f ttl -s PPODtest2.yaml PPOD0e.ttl` it generates the error message 

```
Traceback (most recent call last):
  File "/media/adh/Elements/WorkFromHome/ASI/ConservationOntology/CaPPOD/PPODLinkML/bin/linkml-validate", line 8, in <module>
    sys.exit(cli())
  File "/media/adh/Elements/WorkFromHome/ASI/ConservationOntology/CaPPOD/PPODLinkML/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/media/adh/Elements/WorkFromHome/ASI/ConservationOntology/CaPPOD/PPODLinkML/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/media/adh/Elements/WorkFromHome/ASI/ConservationOntology/CaPPOD/PPODLinkML/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/media/adh/Elements/WorkFromHome/ASI/ConservationOntology/CaPPOD/PPODLinkML/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/media/adh/Elements/WorkFromHome/ASI/ConservationOntology/CaPPOD/PPODLinkML/lib/python3.8/site-packages/linkml/validators/jsonschemavalidator.py", line 143, in cli
    obj = loader.load(source=input, target_class=py_target_class, **inargs)
  File "/media/adh/Elements/WorkFromHome/ASI/ConservationOntology/CaPPOD/PPODLinkML/lib/python3.8/site-packages/linkml_runtime/loaders/rdflib_loader.py", line 240, in load
    objs = self.from_rdf_graph(g, schemaview=schemaview, target_class=target_class, prefix_map=prefix_map, **kwargs)
  File "/media/adh/Elements/WorkFromHome/ASI/ConservationOntology/CaPPOD/PPODLinkML/lib/python3.8/site-packages/linkml_runtime/loaders/rdflib_loader.py", line 82, in from_rdf_graph
    dict_obj = self._get_id_dict(subject, schemaview, subject_class)
  File "/media/adh/Elements/WorkFromHome/ASI/ConservationOntology/CaPPOD/PPODLinkML/lib/python3.8/site-packages/linkml_runtime/loaders/rdflib_loader.py", line 204, in _get_id_dict
    return {id_slot.name: id_val}
AttributeError: 'NoneType' object has no attribute 'name'
```

The input data are the following: the schema PPODtest2.yaml is

```
# PPOD LinkML schema

id: https://github.com/adhollander/ppod 
name: PPOD
prefixes:
  linkml: https://w3id.org/linkml/
  dcterms: http://purl.org/dc/terms/
  core: http://vivoweb.org/ontology/core#
  fsls: https://raw.githubusercontent.com/adhollander/FSLschemas/main/fsisupp.owl#
  poder: http://poderopedia.com/vocab/
  rdfs: http://www.w3.org/2000/01/rdf-schema#

imports: 
  - linkml:types
default_range: string

classes:
  Container:
    class_uri: fsls:Container
    tree_root: true
    slots:
      - datasets 

  Dataset:
    class_uri: core:Dataset
    slots:
      - title
      - label
      - has URL

slots:
  datasets:
    slot_uri: fsls:datasets
    multivalued: true
    inlined_as_list: true
    range: Dataset

  title:
    required: true
    description: name of the entity
    slot_uri: dcterms:title
  label:
    required: true
    description: a captioning label for the entity
    slot_uri: rdfs:label
    multivalued: true
  has URL: 
    description: URL of the entity 
    slot_uri: poder:hasURL
    multivalued: true
    range: uriorcurie
```
and the test data PPOD0e.ttl is the following

```
@prefix core: <http://vivoweb.org/ontology/core#> .
@prefix fslp: <https://raw.githubusercontent.com/adhollander/FSLschemas/main/CA_PPODterms.ttl#> .
@prefix fsls: <https://raw.githubusercontent.com/adhollander/FSLschemas/main/fsisupp.owl#> .
@prefix ns2: <http://purl.org/dc/terms/> .
@prefix poder: <http://poderopedia.com/vocab/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .


fsls:root a fsls:Container ;
    fsls:datasets fslp:dat_2cbb44 .

fslp:dat_2cbb44 a core:Dataset ;
    rdfs:label "gridMET" ;
    poder:hasURL <http://www.climatologylab.org/gridmet.html> ;
    ns2:title "gridMET" .
```
I have tested this on LinkML 1.4.3 using RDFLib 6.2, running on Linux Mint 20.3. I think this error is getting generated in line 401 of query.py in RDFLib, but I don't have much understanding of what would be causing this error.

**Comment by cmungall** [comment]
oh dear, that's not a very informative error.

We'll investigate more later, but I am pretty sure this will be solved by making an identifier slot in the schema for both classes. These are not translated to triples, but are used to determine the IRI of the subject of the triples. Without an identifier, ->ttl will generate blank nodes. The behavior for ttl-> when non-blank nodes are encountered where an identifier is expected should indeed generate an error, but a friendlier one.

**Comment by adhollander** [comment]
I think that does the trick. In my test case above added an identifier slot to the Container and Dataset classes and made matching adjustments to the turtle data file. It validates with linkml-validate, and I am able to convert the test data to json or csv with linkml-convert. The next step will be to try this after making changes to my full dataset and LinkML schema.

**Comment by sierra-moxon** [comment]
@adhollander - do you think you have what you need here so that we may close this ticket?  Or would you prefer to keep it open until you've fully tested the dataset?

**Comment by adhollander** [comment]
I've gotten past this particular hurdle while working with my full dataset, so you may close the ticket. Thanks!
