### ISSUE TITLE
Validation error if field value starts with inverted comma

### ISSUE THREAD

**Issue by Shalsh23** [linkml/linkml#1307]
**Describe the bug**
On validating yaml data file with linkml schema, if the field value starts with text within inverted commas it throws an error `expected <block end>, but found '<scalar>'`. This error can be resolved by ensuring that the first character of a field value is not `"` or `'`. Inverted commas in the subsequent part of the field value do not cause any error.

**To reproduce**

Below are the sample files that throw this error:
linkml_schema: `flmd_linkml.yaml`
```
id: https://w3id.org/linkml/essdive/flmd
name: flmd_schema
description: schema for file level metadata (flmd) reporting format
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

classes:
  FileLevelMetadata:
    description: file level metadata for a data package uploaded on essdive

    attributes:

      File_Name:
        required: true
        description: Name of the file. 
 
      File_Description:
        description: A brief description of the file.
        required: true

  Container:
    tree_root: true
    description: "list of flmd files"
    attributes:
      flmd_files:
        multivalued: true
        inlined_as_list: true
        range: FileLevelMetadata
```
data_file: `enzymes_dataProcessed_flmd.yml`
```
flmd_files:
    - File_Name: enzymeActivity_corr.csv
      File_Description: "10,368"   corrected measurements of potential activity of the exoenzymes
```
Command:
```
 linkml-validate -s flmd_linkml.yaml enzymes_dataProcessed_flmd.yml
```
Output:
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/linkml-validate", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/linkml/validators/jsonschemavalidator.py", line 143, in cli
    obj = loader.load(source=input, target_class=py_target_class, **inargs)
  File "/opt/homebrew/lib/python3.10/site-packages/linkml_runtime/loaders/loader_root.py", line 85, in load
    results = self.load_any(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/linkml_runtime/loaders/yaml_loader.py", line 32, in load_any
    return self.load_source(source, loader, target_class, accept_header="text/yaml, application/yaml;q=0.9",
  File "/opt/homebrew/lib/python3.10/site-packages/linkml_runtime/loaders/loader_root.py", line 61, in load_source
    data_as_dict = loader(data, metadata)
  File "/opt/homebrew/lib/python3.10/site-packages/linkml_runtime/loaders/yaml_loader.py", line 24, in loader
    return yaml.load(data, DupCheckYamlLoader)
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping

File "enzymes_dataProcessed_flmd.yml", line 2, column 7
expected <block end>, but found '<scalar>'

File "enzymes_dataProcessed_flmd.yml", line 3, column 36
```

This error gets fixed if `"` is not the first character in the value of attribute `File_Description` in data file.

Revised data file: `enzymes_dataProcessed_flmd_revised.yml`
```
flmd_files:
    - File_Name: enzymeActivity_corr.csv
      File_Description: list of "10,368"  corrected measurements of potential activity of the exoenzymes
```
Command:
```
 linkml-validate -s flmd_linkml.yaml enzymes_dataProcessed_flmd_revised.yml
```
Output: Successful validation
```
None
```

**Expected behavior**
Attribute values starting with inverted commas are valid and should be successfully validated using the schema without any errors.

**Comment by cmungall** [comment]
HI @Shalsh23!

I think your example is invalid YAML. You can test this for yourself in https://eemeli.org/yaml-playground/

```
YAMLSyntaxError at line 3, column 7:
  Document is not valid YAML (bad indentation?)
YAMLSyntaxError at line 3, column 7:
  Block collection must not have preceding content here (e.g. directives-end indicator)
```

You can be safe by quoting the string:

```
flmd_files:
    - File_Name: enzymeActivity_corr.csv
      File_Description: '"10,368"   corrected measurements of potential activity of the exoenzymes'
```

**Comment by Shalsh23** [comment]
> HI @Shalsh23!
> 
> I think your example is invalid YAML. You can test this for yourself in https://eemeli.org/yaml-playground/
> 
> ```
> YAMLSyntaxError at line 3, column 7:
>   Document is not valid YAML (bad indentation?)
> YAMLSyntaxError at line 3, column 7:
>   Block collection must not have preceding content here (e.g. directives-end indicator)
> ```
> 
> You can be safe by quoting the string:
> 
> ```
> flmd_files:
>     - File_Name: enzymeActivity_corr.csv
>       File_Description: '"10,368"   corrected measurements of potential activity of the exoenzymes'
> ```

Okay, that helps. Thank you!
