### ISSUE TITLE
Need user-friendly logging for validate command

### ISSUE THREAD

**Issue by Shalsh23** [linkml/linkml#1340]
**Is your feature request related to a problem? Please describe.**
We intend to integrate the validate command with [ESS-DIVE](http://essdive.lbl.gov/) tooling. The goal is to allow our community users to validate the data files before uploading to the ESS-DIVE platform. It is important to have user-friendly logging to make it easy for the community to engage with and adopt these tools.

One of the aspects of such logging would be to, perhaps, replace stack trace with a friendlier message.
For example, below is the output on unsuccessful validation:
```
Loading from ../samples_essdive/enzymes_dataProcessed_flmd_trimmed.tsv
Traceback (most recent call last):
  File "/opt/homebrew/bin/linkml-validate", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/linkml/validators/jsonschemavalidator.py", line 150, in cli
    results = validator.validate_object(obj, target_class=py_target_class)
  File "/opt/homebrew/lib/python3.10/site-packages/linkml/validators/jsonschemavalidator.py", line 51, in validate_object
    return jsonschema.validate(inst_dict, schema=jsonschema_obj, format_checker=jsonschema.Draft7Validator.FORMAT_CHECKER)
  File "/opt/homebrew/lib/python3.10/site-packages/jsonschema/validators.py", line 1121, in validate
    raise error
jsonschema.exceptions.ValidationError: 110.0 is greater than the maximum of 90

Failed validating 'maximum' in schema['properties']['flmd_files']['items']['properties']['Latitude']:
    {'description': 'Coordinate for single point location. This field is '
                    'paired with "Longitude" to create a coordinate pair '
                    'for a single point. All geographic coordinates must '
                    'be provided in WGS84 decimal format. It is strongly '
                    'recommended to record the geographic coordinates in '
                    'the FLMD in cases where the data file does not '
                    'include geographic coordinates and the entire file '
                    'consists of measurements collected at a single '
                    'location. The FLMD Extractor can extract the '
                    'geographic coordinates or bounding box coordinates '
                    'from a CSV file following the CSV Reporting Format.',
     'maximum': 90,
     'minimum': -90,
     'type': 'number'}

On instance['flmd_files'][0]['Latitude']:
    110.0
```
It would be easier for community members to parse the reason for validation failure if they don't have to read through the stack trace. 
@vchendrix Are there any other aspects that would need to be addressed for our community?

**How important is this feature?** Select from the options below:
• Important - not an immediate blocker but important to have before deployment

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term ~ 2 months

**Comment by pkalita-lbl** [comment]
The output of `linkml-validate` was improved in v1.5.6, and it no longer includes a stack trace. I'm going to close this issue but @Shalsh23 if you have ideas for further improvement please feel free to reopen this issue or create a new one!
