### ISSUE TITLE
linkml-convert chokes on TSV data file with quotes _and_ tabs

### ISSUE THREAD

**Issue by matentzn** [linkml/linkml#1373]
**Describe the bug**

When running linkml-convert (from TSV to RDF), an error is thrown when the TSV files have tabs in a literal surrounded by quotes.

Error message:

```
> sh run.sh pip list | grep linkml
linkml                        1.5.0
linkml-dataops                0.1.0
linkml-renderer               0.1.2
linkml-runtime                1.5.0

> sh run.sh make translations/hp-profile-tr.owl
linkml-convert -t rdf -s babelon.yaml -C Profile -S hp-tr.babelon.tsv -o OUT
Loading from translations/hp-tr.babelon.tsv
Traceback (most recent call last):
  File "/usr/local/bin/linkml-convert", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/linkml/utils/converter.py", line 140, in cli
    obj = loader.load(source=input, target_class=py_target_class, **inargs)
  File "/usr/local/lib/python3.10/dist-packages/linkml_runtime/loaders/csv_loader.py", line 43, in load
    objs = unflatten_from_csv(source, config=config, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/json_flattener/flattener.py", line 355, in unflatten_from_csv
    v = v.replace('\\n', '\n').replace('\\t', '\t')
AttributeError: 'list' object has no attribute 'replace'
make: *** [hp.Makefile:561: translations/hp-profile-tr.owl] Error 1
```

**To reproduce**

Data input that fails:

```
source_language	translation_language	subject_id	predicate_id	source_value	translation_value	translation_status
en	tr	HP:0004432	IAO:0000115	ab	"a	b"	CANDIDATE
```

This works:

```
source_language	translation_language	subject_id	predicate_id	source_value	translation_value	translation_status
en	tr	HP:0004432	IAO:0000115	ab	"ab"	CANDIDATE
```

Schema: 
https://github.com/monarch-initiative/babelon/blob/main/src/schema/babelon.yaml

**Expected behavior**

Either a useful error message or a less draconian way to handle the error. 

**Screenshots**
NA

**About your computer (if applicable, please complete the following information):**
 - OS: (ran this is ODK 1.4)

**Additional context**
NA

**Comment by cmungall** [comment]
related: https://stackoverflow.com/questions/65333170/dictreader-should-error-on-wrong-column-count

**Comment by cmungall** [comment]
fixed when json-flattener is next released

but note the issue isn't really anything to do with quotes - it's when the number of values exceeds the number of columns

**Comment by matentzn** [comment]
Great, thank you @cmungall !
