### ISSUE TITLE
Strange linkml-convert serialization problem with slot named "developers".

### ISSUE THREAD

**Issue by ddooley** [linkml/linkml#1396]
**Describe the bug**
The Public Health Alliance for Genomic Epidemiology team is trying out LinkML for describing amplicon scheme specifications.  One bug is coming up for them, the serialization of a "developers" slot is converting its list of objects - people or organizations -  into strings. This still happens even if the range of developers is just People.  Is "developers" somehow a magic keyword?

**To reproduce**

Given: https://github.com/pha4ge/primer-schemes/blob/linkml_ify/schema/primer-scheme.yaml which has: 

<img width="343" alt="image" src="https://user-images.githubusercontent.com/4000582/232245629-4b7a3162-f1ac-44b1-880d-b726b8df733e.png">

and data file: 
https://github.com/pha4ge/primer-schemes/blob/main/sars-cov-2/midnight/v1/info.yml

linkml-convert generates:

linkml-convert -s /Users/bede/Research/Git/primer-schemes/schema/primer-scheme.yaml /Users/bede/Research/Git/primer-schemes/sars-cov-2/midnight/v1/info.yml

The error is below - developers is an **array of strings**, within which it looks like objects were placed.

```
{
  "name": "midnight-v1",
  "schema_version": "0.9.0",
  "organism": "sars-cov-2",
  "developers": [
    "{'person_name': 'Nikki Freed'}",
    "{'person_name': 'Olin Silander'}"
  ],
  "repository_url": "https://github.com/pha4ge/primer-schemes/tree/main/sars-cov-2/midnight/v1",
  "primer_scheme_status": "DEPRECATED",
```

**Expected behavior**
No quotes around items in developers array.

**About your computer (if applicable, please complete the following information):**
Coming soon... getting this from ga4gh team.

**Comment by bede** [comment]
Thanks @ddooley !

I'm encountering this issue with LinkML 1.5.0 installed with Python 3.11 (conda) on MacOS 12.6, running under Rosetta (x86_64) on Apple silicon.

```
% linkml-convert --version 
linkml-convert, version 1.5.0
```

**Comment by cmungall** [comment]
You need to declare `developers` to be `inlined`, and as you are inlining as a list, `inlined_as_list`

This should really be in the FAQ! I make this same mistake all the time!

For now see:

https://linkml.io/linkml/schemas/inlining.html

**Comment by bede** [comment]
Thanks so much @cmungall ! I had tried something along these lines already which triggered further errors – perhaps you can suggest where I was failing?


`developers` now reads as follows:

```yaml
  developers:
    slot_uri: GENEPIO:0100673
    description: Persons or organisations responsible for developing the primer scheme
    required: true
    multivalued: true
    inlined: true
    inlined_as_list: true
    any_of:
      - range: Person
      - range: Organisation
```
I now encounter the following error:

```
% linkml-convert -s /Users/bede/Research/Git/primer-schemes/schema/primer-scheme.yaml /Users/bede/Research/Git/primer-schemes/sars-cov-2/midnight/v1/info.yml
Traceback (most recent call last):
  File "/Users/bede/miniconda3/envs/primaschema/bin/linkml-convert", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/bede/miniconda3/envs/primaschema/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bede/miniconda3/envs/primaschema/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/bede/miniconda3/envs/primaschema/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bede/miniconda3/envs/primaschema/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bede/miniconda3/envs/primaschema/lib/python3.11/site-packages/linkml/utils/converter.py", line 101, in cli
    python_module = PythonGenerator(schema).compile_module()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bede/miniconda3/envs/primaschema/lib/python3.11/site-packages/linkml/generators/pythongen.py", line 76, in compile_module
    pycode = self.serialize(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bede/miniconda3/envs/primaschema/lib/python3.11/site-packages/linkml/utils/generator.py", line 303, in serialize
    self.end_schema(**kwargs)
  File "/Users/bede/miniconda3/envs/primaschema/lib/python3.11/site-packages/linkml/generators/pythongen.py", line 189, in end_schema
    re.sub(r" +\n", "\n", self.gen_schema().replace("\t", "    ")).strip(" "),
                          ^^^^^^^^^^^^^^^^^
  File "/Users/bede/miniconda3/envs/primaschema/lib/python3.11/site-packages/linkml/generators/pythongen.py", line 179, in gen_schema
    {self.gen_classdefs()}
     ^^^^^^^^^^^^^^^^^^^^
  File "/Users/bede/miniconda3/envs/primaschema/lib/python3.11/site-packages/linkml/generators/pythongen.py", line 387, in gen_classdefs
    return "\n".join([self.gen_classdef(v) for v in clist if not v.imported_from])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bede/miniconda3/envs/primaschema/lib/python3.11/site-packages/linkml/generators/pythongen.py", line 387, in <listcomp>
    return "\n".join([self.gen_classdef(v) for v in clist if not v.imported_from])
                      ^^^^^^^^^^^^^^^^^^^^
  File "/Users/bede/miniconda3/envs/primaschema/lib/python3.11/site-packages/linkml/generators/pythongen.py", line 394, in gen_classdef
    postinits = self.gen_postinits(cls)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bede/miniconda3/envs/primaschema/lib/python3.11/site-packages/linkml/generators/pythongen.py", line 712, in gen_postinits
    post_inits.append(self.gen_postinit(cls, slot))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bede/miniconda3/envs/primaschema/lib/python3.11/site-packages/linkml/generators/pythongen.py", line 825, in gen_postinit
    slot_range_cls = self.schema.classes[slot.range]
                     ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'string'
```

I have tried adding string ranges to various child fields without success – might you be able to suggest what remedial action I should take? Thank you again

**Comment by ddooley** [comment]
@cmungall & team, any further advice?  Presumably low level error like this should be trapped anyways?

**Comment by cmungall** [comment]
sorry, am traveling and haven't had a chance to look. Can you take a look @pkalita-lbl 

I think there are some aspects of any_of that need better documented. It wouldn't be a bad idea to make a superclass of both (Agent?) and make that be the "main" range, then refine with the any_of. I believe the support for any_of may be better with pydanticgen

**Comment by pkalita-lbl** [comment]
Chris' assessment is right on the money. The issue here has everything to do with using the range union construct:

```yaml
any_of:
  - range: Person
  - range: Organisation
```

It's somewhat easy for LinkML tools to get a bit confused about a schema author's intent when that construct is used along with the presence (or absence) of a `range` on the slot itself (outside of `any_of`) or a `default_range` on the schema definition (as you have here). 

In particular, your schema has `default_range: string`. Since the `developers` slot has no `range` (outside of `any_of`) it's inferred that its range is `string`. Without going into all the gory details, suffice it to say that causes some confusion deep down in the `gen-python` code (which is called by `linkml-convert`).

Here's an update that illustrates what Chris was suggesting: https://gist.github.com/pkalita-lbl/d348578129c6c460f302c3e3bd26090f I've added a `Developer` class that doesn't really do anything other than act as a superclass for both `Person` and `Organisation`. It can also then serve as the `range` of the `developers` slot to make it clear that it should _not_ inherit the `default_range`. I also updated some of the slot names in the data instance file to agree with the schema and I was able to successfully run it through `linkml-convert`.

**Comment by caufieldjh** [comment]
Thanks for that explanation, @pkalita-lbl - it clears up some persistent issues with `any_of` that I've been seeing, too.

**Comment by bede** [comment]
Thank you all so much! Working great, and I'm cracking on with integrating LinkML into our project 🙏

**Comment by ddooley** [comment]
Ok, I can close this unless LinkML team wants to keep open for some error trapping.

**Comment by bartkl** [comment]
> Chris' assessment is right on the money. The issue here has everything to do with using the range union construct:
> 
> ```yaml
> any_of:
>   - range: Person
>   - range: Organisation
> ```
> 
> It's somewhat easy for LinkML tools to get a bit confused about a schema author's intent when that construct is used along with the presence (or absence) of a `range` on the slot itself (outside of `any_of`) or a `default_range` on the schema definition (as you have here).
> 
> In particular, your schema has `default_range: string`. Since the `developers` slot has no `range` (outside of `any_of`) it's inferred that its range is `string`. Without going into all the gory details, suffice it to say that causes some confusion deep down in the `gen-python` code (which is called by `linkml-convert`).
> 
> Here's an update that illustrates what Chris was suggesting: https://gist.github.com/pkalita-lbl/d348578129c6c460f302c3e3bd26090f I've added a `Developer` class that doesn't really do anything other than act as a superclass for both `Person` and `Organisation`. It can also then serve as the `range` of the `developers` slot to make it clear that it should _not_ inherit the `default_range`. I also updated some of the slot names in the data instance file to agree with the schema and I was able to successfully run it through `linkml-convert`.

Hmm but the schema in the gist is considered invalid by `gen-pydantic` though:

> ValueError: Slot cannot have both range and any_of defined

**Comment by bede** [comment]
Thanks you all for helping so much here. I got a solution working well until LinkML `1.5.3`, given [this model](https://github.com/pha4ge/primer-schemes/blob/056e8f537e70a8400fdad43c29fb2e2c6ba8cb47/schema/primer_scheme.yml) and [these data](https://github.com/pha4ge/primer-schemes/blob/056e8f537e70a8400fdad43c29fb2e2c6ba8cb47/sars-cov-2/midnight/v1/info.yml):

With LinkML `1.5.2`:
_Works as expected without errors_

With LinkML `1.5.3`:
```
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('person_name' was unexpected)

Failed validating 'additionalProperties' in schema['properties']['developers']['items']:
    {'additionalProperties': False,
     'description': '',
     'title': 'Entity',
     'type': 'object'}

On instance['developers'][1]:
    {'person_name': 'Olin Silander'}

```

With LinkML `1.7.8`:
```
linkml.validators.jsonschemavalidator.JsonSchemaDataValidatorError: Additional properties are not allowed ('person_name' was unexpected) in $.developers[0]
Additional properties are not allowed ('person_name' was unexpected) in $.developers[1]
```

Any practical advice would be greatly appreciated, thank you.

**Comment by ddooley** [comment]
@bede Perhaps 'person_name' is not defined as a slot name?  Wondering if this can be closed.

**Comment by bede** [comment]
Hi @cmungall, it is defined as a slot name, but perhaps incorrectly? https://github.com/pha4ge/primer-schemes/blob/056e8f537e70a8400fdad43c29fb2e2c6ba8cb47/schema/primer_scheme.yml#L138

I am using the approach helpfully suggested by @pkalita-lbl ?([model](https://github.com/pha4ge/primer-schemes/blob/056e8f537e70a8400fdad43c29fb2e2c6ba8cb47/schema/primer_scheme.yml), [data](https://github.com/pha4ge/primer-schemes/blob/056e8f537e70a8400fdad43c29fb2e2c6ba8cb47/sars-cov-2/midnight/v1/info.yml))

Might you be able to suggest a better way to model a developer that is either an individual or an organisation? As you can see I'm struggling here.

**Comment by ddooley** [comment]
@bede you have:
<img width="269" alt="image" src="https://github.com/linkml/linkml/assets/4000582/a3e1093c-df17-4310-bab8-3564b31c1e76">
Patrick's example has: 
<img width="220" alt="image" src="https://github.com/linkml/linkml/assets/4000582/c251cf47-99e3-4777-9394-ca94fd34dfe1">
and he has **Developer** as a class:
<img width="278" alt="image" src="https://github.com/linkml/linkml/assets/4000582/b0a4db36-0618-403e-9270-8be2d8f01ec6">
Does that way of treating "Developer" solve this range knowledge issue?

As an aside, I'm wondering if one needs "inlined: true" in addition to " inlined_as_list: true"?

**Comment by nlharris** [comment]
Can this be closed?

**Comment by bede** [comment]
> Does that way of treating "Developer" solve this range knowledge issue?
> 
> As an aside, I'm wondering if one needs "inlined: true" in addition to " inlined_as_list: true"?

Thank you. Alas not – neither approach worked. I've since given up on this structure and am using a list of string fields instead. Thank you all for your efforts here, closing.

**Comment by bede** [comment]
> Can this be closed?

Yes – on mobile at least I cannot see a close button. Thank you

**Comment by cmungall** [comment]
I'm not clear after reading this if there is still a bug or outstanding question? Maybe start a new issue?
