### ISSUE TITLE
Dynamic enums from the documentation fails with `Unknown CellTypeEnum enumeration code`

### ISSUE THREAD

**Issue by cpauvert** [linkml/linkml#1506]
**Describe the bug**
Hello there!
Thanks for developing and maintaining LinkML!

I'm really interested in the [dynamic enums](https://linkml.io/linkml/schemas/enums.html#dynamic-enums) feature of LinkML. While I understand that not all the tooling is available (blog [post](https://douroucouli.wordpress.com/2022/07/15/using-ontologies-within-data-models-and-standards/), #1017), the documentation indicates:

> At this time, tooling support for dynamic enums is maturing, but **you can still go ahead and use them in your schemas**. **The default behavior will be too permissive** – however, you still gain additional clarity in your schema documentation.
>
> https://linkml.io/linkml/schemas/enums.html#tooling-to-support-dynamic-enums (emphasis is on me)

So, I expected the example from the documentation to pass the validation, even if not all the checks are implemented yet. But the validation (or conversion) failed with:

```python
Traceback (most recent call last):
  File "/home/cpauvert/miniconda3/bin/linkml-validate", line 8, in <module>
    sys.exit(cli())
  File "/home/cpauvert/miniconda3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/cpauvert/miniconda3/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/cpauvert/miniconda3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cpauvert/miniconda3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/cpauvert/miniconda3/lib/python3.9/site-packages/linkml/validators/jsonschemavalidator.py", line 160, in cli
    obj = loader.load(source=input, target_class=py_target_class, **inargs)
  File "/home/cpauvert/miniconda3/lib/python3.9/site-packages/linkml_runtime/loaders/loader_root.py", line 95, in load
    results = self.load_any(*args, **kwargs)
  File "/home/cpauvert/miniconda3/lib/python3.9/site-packages/linkml_runtime/loaders/yaml_loader.py", line 35, in load_any
    return self.load_source(source, loader, target_class, accept_header="text/yaml, application/yaml;q=0.9",
  File "/home/cpauvert/miniconda3/lib/python3.9/site-packages/linkml_runtime/loaders/loader_root.py", line 76, in load_source
    return target_class(**data_as_dict)
  File "<string>", line 4, in __init__
  File "test", line 58, in __post_init__
  File "/home/cpauvert/miniconda3/lib/python3.9/site-packages/linkml_runtime/utils/enumerations.py", line 52, in __init__
    raise ValueError(f"Unknown {self.__class__.__name__} enumeration code: {key}")
ValueError: Unknown CellTypeEnum enumeration code: CL:0000109
```

**To reproduce**
I use the first example of the FAQ entry: https://linkml.io/linkml/faq/modeling.html#how-do-i-constrain-a-slot-to-a-branch-of-an-ontology-or-a-whole-ontology that is available as a gist:  https://gist.github.com/cpauvert/bb014f7b96c77865148f3899028ba6ce

1. Go to  https://gist.github.com/cpauvert/bb014f7b96c77865148f3899028ba6ce to get a reprex of the schema and a small data
2. Run `linkml-validate -s dynamic_enums.yaml dynamic_enums_data.yaml`
3. See error

**Expected behavior**
Validation of the data against the schema

**Additional context**
LinkML v1.5.5

BEst,

**Comment by cpauvert** [comment]
Changing the `dynamic enum` to a `type`, as in the second example of the  [FAQ](https://linkml.io/linkml/faq/modeling.html#how-do-i-constrain-a-slot-to-a-branch-of-an-ontology-or-a-whole-ontology) enable a correct validation of the toy data provided, but this is not a satisfying workaround. But maybe the only solution yet: https://github.com/linkml/linkml/issues/1112#issuecomment-1318879538 ??


```yaml
types:
  CellTypeId:
    typeof: uriorcurie
    pattern: '^CL:\d+$'

slots:
  cell_type:
    range: CellTypeId
```
