### ISSUE TITLE
A slot requirement cannot be removed on a subclass

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#1508]
**Describe the bug**
I've declared a slot as `required: true` in a class, then I've created a child class where I'm replacing that slot with a child slot. Marking in the child class the parent slot as `required: false` (because it's being replaced by a child slot) doesn't work.

1. Create schema
<details>
  <summary>schema.yaml</summary>

``` yaml
# schema.yaml
id: http://example.org/tank
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

slots:
  wheels:
    required: true
  chains:
    is_a: wheels
    required: true
classes:
  Vehicle:
    slots:
      - wheels
  Tank:
    is_a: Vehicle
    slots:
      - chains
    slot_usage:
      wheels:
        required: false
      chains:
        required: true
``` 
 </details>

2. Instanciate a `tank`:

``` yaml
# tank.yaml
chains: something
```

3. Try to validate the `tank` against the schema
``` shell
linkml-validate --target-class Tank --schema schema.yaml tank.yaml
```

4. Observe the validation failing:

<details>
  <summary>validation error</summary>

``` shell
Traceback (most recent call last):
  File "/opt/homebrew/bin/linkml-validate", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/linkml/validators/jsonschemavalidator.py", line 160, in cli
    obj = loader.load(source=input, target_class=py_target_class, **inargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/linkml_runtime/loaders/loader_root.py", line 95, in load
    results = self.load_any(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/linkml_runtime/loaders/yaml_loader.py", line 35, in load_any
    return self.load_source(source, loader, target_class, accept_header="text/yaml, application/yaml;q=0.9",
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/linkml_runtime/loaders/loader_root.py", line 76, in load_source
    return target_class(**data_as_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 5, in __init__
  File "test", line 82, in __post_init__
  File "/opt/homebrew/lib/python3.11/site-packages/linkml_runtime/utils/yamlutils.py", line 273, in MissingRequiredField
    raise ValueError(f"{field_name} must be supplied")
ValueError: wheels must be supplied
```
 </details>

# Expected behavior
I'd expect `tank`s not to be required to have `wheels` (that why it's not required in the `tank` class), but `chain`s (which I've declared to be as a wheel).

# About your computer
 - LinkML Version: 1.5.5

**Comment by Silvanoc** [comment]
I've also created a small Bash script to reproduce the issue on my side, you might be interested on it (you'll want to remove the `.txt` extension):
[demo-slot-inheritance.bash.txt](https://github.com/linkml/linkml/files/11829821/demo-slot-inheritance.bash.txt)

**Comment by Silvanoc** [comment]
> It is also not possible to remove a slot requirement if the requirement is set in the definition of the slot and then removed using slot_usage.

I'm sorry, but I don't see the difference with what I'm reporting 🙂

**Comment by cmungall** [comment]
Thanks for the report and confirmation!

This definitely needs to be better documented, but this behavior is expected, since subclassing and slot usage are intended to *refine* rather than *override*. Formally,[non-monotonic inference](https://en.wikipedia.org/wiki/Non-monotonic_logic) is not supported.

The framework should definitely do a better job of warning you when you attempt to do this, rather than surprising you at validation time.

We're interested in collecting use cases for allowing for limited non-monotonicity in the future. There are known gotchas here, e.g. [the diamond problem](https://en.wikipedia.org/wiki/Multiple_inheritance#The_diamond_problem). For now, it is possible to rewrite your schema to avoid non-monotonicity (e.g. by having a neutral parent and explicitly restrictive or non-restrictive subclasses)? Or does this lead to awkwardness or non-intuitive schemas? If the latter please post here as these are useful for us when planning this!

**Comment by Silvanoc** [comment]
The time I reported this issue, I wasn't fully understanding LinkML expectations. @turbomam made me aware that it wasn't supposed to work due to the fact that non-monotonic inferences are not supported. But still proposed me to file this issue as a reminder for better documenting/reporting. That's the only reason why this issue remains open. Otherwise I'd close it.

**Comment by cmungall** [comment]
Thanks, much appreciated! Let’s close when we have a faq entry or other
similar docs

**Comment by AlasdairGray** [comment]
> > It is also not possible to remove a slot requirement if the requirement is set in the definition of the slot and then removed using slot_usage.
> 
> I'm sorry, but I don't see the difference with what I'm reporting 🙂

We are not using class inheritance but trying to reuse a slot in two different classes. So it is the same underlying issue but for a different use case.

**Comment by AlasdairGray** [comment]
In our use case, we have two mutually exclusive branches of a class hierarchy that are both using the same common property. We would like to declare the slot in the way that it is most commonly going to be used so that the page for the slot would show the common usage, in our use case this would be that the slot is required. We then try to override the usage of the slot on the other branch.

**Comment by cmungall** [comment]
I'd recommend making the core slot have the most relaxed definition. How I
appreciate that it is useful to see the most common usage on the slot page.
If there were better display of usages on the common slot page would that
go some way to address your concerns?

**Comment by AlasdairGray** [comment]
The slot usage table is a bit confusing at the moment. We have decided to update our template so that every class that uses the slot has a separate row with the obligation and cardinality displayed explicitly. It works for us as we only have 4 or 5 classes and 30 odd slots. It may not work for others.

**Comment by candleindark** [comment]
As of `linkml` @ version 1.8.2. monotonicity in schemas doesn't seem to be enforced in `linkml-validate`. In this version of `linkml`, you can run `linkml-validate` against the schemas and the corresponding data instances given by @Silvanoc and @AlasdairGray without any validation error. However, you will still encounter validation errors if you run `linkml-convert` to convert the aforementioned data instances to a different format.

To make the point more clear. Consider the following.

1. Create the schema
<details> 
<summary>personinfo.yaml</summary>

```yaml
# personinfo.yaml

id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
  personinfo: https://w3id.org/linkml/examples/personinfo
imports:
  - linkml:types
default_range: string
default_prefix: personinfo

slots:
  age:
    description: Age of a person  # To be overridden later
    range: string  # To be overridden later
  phone:
    required: true  # To be overridden later

classes:
  Person:
    attributes:
      id:
      full_name:
      aliases:
    slots:
      - age
      - phone
    slot_usage:
      age:
        range: integer # overriding
  Man:
    is_a: Person
    slot_usage:
      age:
        description: "Age of a man"  # overriding
      phone:
        required: false  # overriding
```
</details>

2. Create data instance
<details>
<summary>data.yaml</summary>

```yaml
# data.yaml

id: ORCID:1234
full_name: Clark Kent
age: 32
```
</details>

3. Running `linkml-validate --target-class Man -s personinfo.yaml data.yaml` produces
<details>
<summary>output</summary>

```console
No issues found
```
</details>

4. Running `linkml-convert -s personinfo.yaml -o data.json -C Man data.yaml` produces
<details>
<summary>output</summary> 

```console
Traceback (most recent call last):
  File "/Users/isaac/.pyenv/versions/linkml-tutorial/bin/linkml-convert", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/isaac/.pyenv/versions/linkml-tutorial/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isaac/.pyenv/versions/linkml-tutorial/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/isaac/.pyenv/versions/linkml-tutorial/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isaac/.pyenv/versions/linkml-tutorial/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isaac/.pyenv/versions/linkml-tutorial/lib/python3.11/site-packages/linkml/utils/converter.py", line 145, in cli
    obj = loader.load(source=input, target_class=py_target_class, **inargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isaac/.pyenv/versions/linkml-tutorial/lib/python3.11/site-packages/linkml_runtime/loaders/loader_root.py", line 76, in load
    results = self.load_any(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isaac/.pyenv/versions/linkml-tutorial/lib/python3.11/site-packages/linkml_runtime/loaders/yaml_loader.py", line 42, in load_any
    return self._construct_target_class(data_as_dict, target_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isaac/.pyenv/versions/linkml-tutorial/lib/python3.11/site-packages/linkml_runtime/loaders/loader_root.py", line 137, in _construct_target_class
    return target_class(**data_as_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __init__
  File "test", line 95, in __post_init__
  File "/Users/isaac/.pyenv/versions/linkml-tutorial/lib/python3.11/site-packages/linkml_runtime/utils/yamlutils.py", line 281, in MissingRequiredField
    raise ValueError(f"{field_name} must be supplied")
ValueError: phone must be supplied
```
</details>

5. Additionally running `gen-json-schema -t Man personinfo.yaml` produces a schema showing that monotonicity is not enforced, i.e. overriding is allowed.
<details>
<summary>json schema</summary>

```json
{
    "$defs": {
        "Man": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "age": {
                    "description": "Age of a man",
                    "type": [
                        "integer",
                        "null"
                    ]
                },
                "aliases": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "full_name": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "id": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "phone": {
                    "type": [
                        "string",
                        "null"
                    ]
                }
            },
            "title": "Man",
            "type": "object"
        },
        "Person": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "age": {
                    "description": "Age of a person",
                    "type": [
                        "integer",
                        "null"
                    ]
                },
                "aliases": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "full_name": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "id": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "phone": {
                    "type": "string"
                }
            },
            "required": [
                "phone"
            ],
            "title": "Person",
            "type": "object"
        }
    },
    "$id": "https://w3id.org/linkml/examples/personinfo",
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "additionalProperties": true,
    "description": "",
    "metamodel_version": "1.7.0",
    "properties": {
        "age": {
            "description": "Age of a man",
            "type": [
                "integer",
                "null"
            ]
        },
        "aliases": {
            "type": [
                "string",
                "null"
            ]
        },
        "full_name": {
            "type": [
                "string",
                "null"
            ]
        },
        "id": {
            "type": [
                "string",
                "null"
            ]
        },
        "phone": {
            "type": [
                "string",
                "null"
            ]
        }
    },
    "title": "personinfo",
    "type": "object",
    "version": null
}
```
</details>

Are these outcomes result of a bug in `linkml-validate` or LinkML starting to support non-monotonic references?

**Comment by candleindark** [comment]
Is the monotonicity behavior of LinkML going to be enforced again? Currently, at `linkml, version 1.10.0`, my post about non-enforcement of monotonicity, https://github.com/linkml/linkml/issues/1508#issuecomment-2292431671, is still valid.

**Comment by Silvanoc** [comment]
> Is the monotonicity behavior of LinkML going to be enforced again? Currently, at `linkml, version 1.10.0`, my post about non-enforcement of monotonicity, [#1508 (comment)](https://github.com/linkml/linkml/issues/1508#issuecomment-2292431671), is still valid.

I suppose that we are only missing someone working on it. It's a question of prioritization. I mean, I'm a contributor and I reported this issue, but it's not that way up in my priority list so that I work on it. I don't know if there's someone else in the community wanting to take this over.

**Comment by candleindark** [comment]
> I suppose that we are only missing someone working on it. It's a question of prioritization.

Is the intent still to enforce monotonicity in LinkML though?

@Silvanoc The current behavior is very different than when you first reported the issue. Currently, monotonicity is hardly enforced at all. In my read of the documentation the intended behavior is
1. all slots in [`SlotDefinition`](https://linkml.io/linkml-model/latest/docs/SlotDefinition/) except those in [`SlotExpression`](https://linkml.io/linkml-model/latest/docs/SlotExpression/) can be overridden. 
2. The ones in [`SlotExpression`](https://linkml.io/linkml-model/latest/docs/SlotExpression/) exhibit the monotonicity behavior. 

However, currently, in the implementation of LinkML, many of the slots in [`SlotExpression`](https://linkml.io/linkml-model/latest/docs/SlotExpression/) can be overridden.

**Comment by yarikoptic** [comment]
Is there a term for "monotonicity" in sense of becoming more and more restrictive, not retaining the same level of restriction?  

What I see is happening with any subclassing is that you are limiting the space more and making it more specific.  

So it is ok for parent to be less restrictive, and thus more generic: e.g. Car (subclass of) is a more restrictive Vehicle.  I think it is Ok for Vehicle to have any number of wheels. Then for Car to restrict it to be 3+ (or 4+).

So, overall enforcing monotonicity should boil down IMHO to allowing for increasing restrictiveness of the model. So in the hypothetical mentioned above Diamond case it would be the "overlap" among **all** restrictions across parents, pretty much the **and** rule.  `required` is a bit odd, but if you consider its bool negative -- "optional" thus starting without restriction, any added restriction of "optional: False" would make `and` on it requiring the field (more restrictions).

**Comment by cmungall** [comment]
The intent is to discourage monotonicity, to provide mechanisms to clearly flag where it occurs, to better document pitfalls (diamonds, conversion to OWA frameworks such as OWL).

> So it is ok for parent to be less restrictive, and thus more generic: e.g. Car (subclass of) is a more restrictive Vehicle. I think it is Ok for Vehicle to have any number of wheels. Then for Car to restrict it to be 3+ (or 4+).

correct

> So, overall enforcing monotonicity should boil down IMHO to allowing for increasing restrictiveness of the model. So in the hypothetical mentioned above Diamond case it would be the "overlap" among all restrictions across parents, pretty much the and rule.

exactly

> required is a bit odd, but if you consider its bool negative -- "optional" thus starting without restriction, any added restriction of "optional: False" would make and on it requiring the field (more restrictions).

here's another way of thinking about it: only `required: true` has a logical interpretation. `required: false` is logically silent. Expect more clarification on this coming soon!
