### ISSUE TITLE
Package linkml==1.5.7 seems more broken than 1.5.6

### ISSUE THREAD

**Issue by jeffhhk** [linkml/linkml#1644]
**Describe the bug**
Package linkml==1.5.7 seems more broken than 1.5.6

**To reproduce**

    pip install linkml==1.5.7
        . . .
        Successfully installed linkml-1.5.7
    python -c 'from linkml.utils import validation'
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/home/jeff/.pyenv/versions/3.7.9/envs/linkml/lib/python3.7/site-packages/linkml/utils/validation.py", line 9, in <module>
            from linkml.generators.jsonschemagen import JsonSchemaGenerator
          File "/home/jeff/.pyenv/versions/3.7.9/envs/linkml/lib/python3.7/site-packages/linkml/generators/__init__.py", line 6, in <module>
            from linkml.generators.javagen import JavaGenerator
          File "/home/jeff/.pyenv/versions/3.7.9/envs/linkml/lib/python3.7/site-packages/linkml/generators/javagen.py", line 11, in <module>
            from linkml.generators.oocodegen import OOCodeGenerator
          File "/home/jeff/.pyenv/versions/3.7.9/envs/linkml/lib/python3.7/site-packages/linkml/generators/oocodegen.py", line 18, in <module>
            from linkml.utils.generator import Generator
          File "/home/jeff/.pyenv/versions/3.7.9/envs/linkml/lib/python3.7/site-packages/linkml/utils/generator.py", line 62, in <module>
            @lru_cache
          File "/home/jeff/.pyenv/versions/3.7.9/lib/python3.7/functools.py", line 490, in lru_cache
            raise TypeError('Expected maxsize to be an integer or None')
        TypeError: Expected maxsize to be an integer or None
    
**Expected behavior**

    pip install linkml==1.5.6
        . . .
        Successfully installed linkml-1.5.6
    python -c 'from linkml.utils import validation'
    echo $?
        0

**Screenshots**
n/a

**About your computer (if applicable, please complete the following information):**

    uname -a
        Linux carbonara 5.15.0-83-generic #92~20.04.1-Ubuntu SMP Mon Aug 21 14:00:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
    python -V
        Python 3.7.9

**Additional context**

**Comment by pkalita-lbl** [comment]
Hi @jeffhhk! Python 3.7 reached [end-of-life status](https://devguide.python.org/versions/) earlier this year. As such we will be dropping support for it entirely soon: https://github.com/linkml/linkml/issues/1519. If you're able to upgrade to Python 3.8 or later I think you'll have a better experience!

**Comment by jeffhhk** [comment]
Confirmed that this works:

    pyenv virtualenv 3.9.7 linkml2
    pyenv local 3.9.7/envs/linkml2
    pip install linkml==1.5.7
    python -c 'from linkml.utils import validation'
