### ISSUE TITLE
`linkml2schemasheets-template` failing in MIxS 6.2 RC with LinkML 1.6 (initial report)

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1652]
https://github.com/GenomicsStandardsConsortium/mixs6.2_release_candidate

```shell
poetry run linkml2schemasheets-template \
        --debug-report-path other-reports/notated-populated-generated-debug-report.yaml \
        --log-file other-reports/populated-with-generated-spec-log.txt \
        --output-path schemasheets-usage-output/mixs_6_2_rc-concise-usage-for-text-mining.tsv.tmp \
        --report-style concise \
        --source-path generated-schema/mixs_6_2_rc.yaml
```

> Traceback (most recent call last):
>   File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-T9l08Vg6-py3.9/bin/linkml2schemasheets-template", line 8, in <module>
>     sys.exit(cli())
>   File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-T9l08Vg6-py3.9/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-T9l08Vg6-py3.9/lib/python3.9/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-T9l08Vg6-py3.9/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-T9l08Vg6-py3.9/lib/python3.9/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-T9l08Vg6-py3.9/lib/python3.9/site-packages/schemasheets/generate_populate.py", line 356, in cli
>     current_exporter.export(
>   File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-T9l08Vg6-py3.9/lib/python3.9/site-packages/schemasheets/schema_exporter.py", line 148, in export
>     self.export_element(su, cls, schemaview, table_config)
>   File "/home/mark/.cache/pypoetry/virtualenvs/mixs-envo-struct-knowl-extraction-T9l08Vg6-py3.9/lib/python3.9/site-packages/schemasheets/schema_exporter.py", line 288, in export_element
>     v = '|'.join(v)
> TypeError: sequence item 0: expected str instance, extended_float found
> make: *** [project.Makefile:160: schemasheets-usage-output/mixs_6_2_rc-concise-usage-for-text-mining.tsv] Error 1
>

**Comment by turbomam** [comment]
build a throwaway list in which element is asserted to be a string

**Comment by turbomam** [comment]
`v = '|'.join(v)`

becomes

`v = '|'.join([str(i) for i in v])`
