### ISSUE TITLE
gen-pydantic fails on example code

### ISSUE THREAD

**Issue by plbremer** [linkml/linkml#1728]
**Describe the bug**
Taking the example .yaml from https://linkml.io/linkml/intro/tutorial05.html, but using the command described here https://linkml.io/linkml/generators/pydantic.html, e.g.

`gen-pydantic person.yaml > person.py`

we get an immediate failure running person.py

```
INFO:root:Using SchemaView with im=None
INFO:root:Importing linkml:types as /Users/pgleasonbremer/Library/Caches/pypoetry/virtualenvs/alo--uCTBReF-py3.11/lib/python3.11/site-packages/linkml_runtime/linkml_model/model/schema/types from source person.yaml; base_dir=None
(alo-py3.11) pgleasonbremer@BAI-R6M3H4XLPD delete_another_one % python3 person.py 
Traceback (most recent call last):
  File "/Users/pgleasonbremer/delete_another_one/person.py", line 19, in <module>
    class ConfiguredBaseModel(WeakRefShimBaseModel,
  File "/Users/pgleasonbremer/Library/Caches/pypoetry/virtualenvs/alo--uCTBReF-py3.11/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 123, in __new__
    cls: type[BaseModel] = super().__new__(mcs, cls_name, bases, namespace, **kwargs)  # type: ignore
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 106, in __new__
TypeError: ConfiguredBaseModel.__init_subclass__() takes no keyword arguments
```

**To reproduce**
1. setup a poetry environment like 

```
[tool.poetry]
name = "alo"
version = "0.1.3"
description = "This is ALO model with general purpose classes and properties."
authors = ["Nolan Nichols <nnichols@altoslabs.com>"]
license = "MIT"
readme = "README.md"
include = ["README.md", "src/alo/schema", "project"]

[tool.poetry.dependencies]
python = "^3.9"
linkml-runtime = "^1.1.24"

[tool.poetry.group.dev.dependencies]
linkml = "^1.5.7"

[tool.poetry.dev-dependencies]
linkml = "^1.3.7"
mkdocs-material = "^8.2.8"
mkdocs-mermaid2-plugin = "^0.6.0"
schemasheets = "^0.1.14"
ipykernel = "^6.25.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
docs = ["linkml", "mkdocs-material"]
```

2. create the example .yaml

```
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:                                  ## Note are adding 3 new ones here
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/
  personinfo: https://w3id.org/linkml/examples/personinfo/
  ORCID: https://orcid.org/
imports:
  - linkml:types
default_range: string
  
classes:
  Person:
    class_uri: schema:Person              ## reuse schema.org vocabulary
    attributes:
      id:
        identifier: true
      full_name:
        required: true
        description:
          name of the person
        slot_uri: schema:name             ## reuse schema.org vocabulary
      aliases:
        multivalued: true
        description:
          other names for the person
      phone:
        pattern: "^[\\d\\(\\)\\-]+$"
        slot_uri: schema:telephone       ## reuse schema.org vocabulary
      age:
        range: integer
        minimum_value: 0
        maximum_value: 200
    id_prefixes:
      - ORCID
  Container:
    attributes:
      persons:
        multivalued: true
        inlined_as_list: true
        range: Person
```
3. create the pydantic representation
`gen-pydantic person.yaml > person.py`
4. try to run or import the person.py
`python person.py`

**Expected behavior**
No errors

**About your computer (if applicable, please complete the following information):**
MacOS Ventura

**Comment by plbremer** [comment]
`gen-pydantic person.yaml > person.py --pydantic_version 2` resolved for me
