### ISSUE TITLE
SQLDDLGenerator fails in tccm test

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#184]
The SQLDDL Generator produces the stack trace below.  I have temporarily disabled this check in `test_tccm_issues` for the time being

```
Traceback (most recent call last):
  File "/../git/zzlinkml/linkml/tests/test_issues/test_tccm_issues.py", line 66, in test_minimal_model
    env.generate_single_file(['issue_tccm', 'minimalmodel.' + generator.valid_formats[0]],
  File "/../git/zzlinkml/linkml/tests/utils/test_environment.py", line 217, in generate_single_file
    actual = generator()
  File "/../git/zzlinkml/linkml/tests/test_issues/test_tccm_issues.py", line 67, in <lambda>
    lambda: generator(env.input_path('issue_tccm', 'minimalmodel.yaml'),
  File "/../git/zzlinkml/linkml/linkml/utils/generator.py", line 132, in serialize
    self.end_schema(**kwargs)
  File "/../git/zzlinkml/linkml/linkml/generators/sqlddlgen.py", line 54, in end_schema
    Table(t, schema_metadata,
  File "<string>", line 2, in __new__
  File "/../git/zzlinkml/linkml/.tox/py39/.venv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/../git/zzlinkml/linkml/.tox/py39/.venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 600, in __new__
    metadata._remove_table(name, schema)
  File "/../git/zzlinkml/linkml/.tox/py39/.venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/../git/zzlinkml/linkml/.tox/py39/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/../git/zzlinkml/linkml/.tox/py39/.venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 595, in __new__
    table._init(name, metadata, *args, **kw)
  File "/../git/zzlinkml/linkml/.tox/py39/.venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 681, in _init
    self._init_items(
  File "/../git/zzlinkml/linkml/.tox/py39/.venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 134, in _init_items
    spwd(self, **kw)
  File "/../git/zzlinkml/linkml/.tox/py39/.venv/lib/python3.9/site-packages/sqlalchemy/sql/base.py", line 1023, in _set_parent_with_dispatch
    self._set_parent(parent, **kw)
  File "/../git/zzlinkml/linkml/.tox/py39/.venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 1756, in _set_parent
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Column object 'id' already assigned to Table 'Address'
```

**Comment by sierra-moxon** [comment]
I can't seem to find this test - test_tccm_issues nor test_tccm_issue.  apologies if I am being dumb!
