### ISSUE TITLE
query about initial generation of online schema definition

### ISSUE THREAD

**Issue by druimalban** [linkml/linkml#1965]
I originally put the issue here (https://github.com/linkml/linkml-model/issues/191) but I then noticed a message there, that you want to have them here. Nonetheless, my issue does not strictly refer to LinkML usage/features, but to initial development of online schemata and the LinkML schema proper, so I haven't deleted it from there.

----
I have been developing my own data model, and I'm having a bit of trouble understanding how the initial online schema is generated.

From the makefile, as far as I understand, you do this:

1. Run linkml `gen-project` on the `meta.yaml`, which in turn depends on all of the other yaml definitions, like `linkml:types`, `linkml:units`;
2. Run linkml `gen-doc` from the project directory, which generates markdown files;
3. Call `mkdocs` on the generated markdown files.

However, the calls in `meta.yaml` are via the imports directive, which, in the default behavior (going by the gen-project help command, I can't see any other behavior), will fetch these from the URL provided.

This suggests to me that, when you were developing LinkML, you bootstrapped the schema somehow, which generated the initial online definition.

I can work around this by generating documentation for each YAML schema (either manually or in a makefile), and putting it on a local web server (some directory like `localhost/schema` or similar). This is OK for one schema, like your schema.org example, but it becomes increasingly difficult, even with a makefile, for 12 or more different 'child' schemata.

What is the process of generating the schema, in absence of an extant online schema? Is there a way to feed it a directory of YAML schemata which will produce something like [`w3id.org/linkml`](https://w3id.org/linkml/)?

**Comment by druimalban** [comment]
Aha, brilliant! Thanks. That solves our problem of not having a good place to put our schema yet.

However, it's not clear to me how the sub-schemata actually get built?

I think I'm getting really confused by the following:

[meta.yaml, line 70](https://github.com/linkml/linkml-model/blob/main/linkml_model/model/schema/meta.yaml#L70) has the following imports: `linkml:types`; `linkml:mappings`; `linkml:extensions`; `linkml:annotations`; `linkml:validation`; `linkml:units`.

My understanding is that these should be expanded to `https://w3id.org/linkml/{types,mappings,...}`, something like this for the ubiquitous `linkml:types`: `linkml:types` -> `https://w3id.org/linkml/types` -> `https://linkml.io/linkml-model/latest/docs/types/`.

However, while most of these do exist as a canonical URI, including linkml:units  does not. It 404s. This suggests to me that calls like linkml:types are actually calls to slots, which have been imported from somewhere.

If it is the case that a call like linkml:types is related to a slot, how are we able to substitute an import like `myschema:subschema` for `./subschema`?

For context, the data model in my head works like this:
- A core schema defining a shape of a typical file which is validated against the schema.
- A second schema which defines specific types of column (in this case, I want to say that a given column is one which consists of collected data, or a column is one which consists of simulated data).
- A schema provided by someone else, against which I actually validate data files. This schema e.g. provides definitions of columns (e.g. in CSVs) such as "site ID" or "local site name".

**Comment by cmungall** [comment]
there is also an ability to specify a lookup table that maps URIs to local file paths, which can be useful if you want to specify CURIE/URI rather than relative importants, will be documented soon...

**Comment by druimalban** [comment]
As regards to local paths: https://github.com/linkml/linkml/issues/2024

**Comment by druimalban** [comment]
So, further to the above:

Having written a very quick Python script which does the following, apparently as the `gen-rdf` works:

```python
gen = RDFGenerator (schema = args.meta, format = "ttl", context = args.context, log_level = logging.INFO)
gen.serialize(output = args.output)
```

I have a local (nginx) web server which is serving the YAML, JSON-LD contexts, &c. I spent a long time trying to catch the urllib errors with setting the logger &c., to no avail.

It has the following simple rewrite rules, essentially a simple redirect to subdirectories `jsonld`, `schema` &c., which are the source of the messages in the logs which will follow:

```conf
rewrite ^/saved/([^/]+)\.yaml$ /saved/schema/$1.yaml;
rewrite ^/saved/(.*\.?)context.json$ /saved/jsonld/$1context.jsonld;
rewrite ^/saved/(.*\.?)context.jsonld$ /saved/jsonld/$1context.jsonld;
rewrite ^/saved/(.*)\.schema.json$ /saved/jsonschema/$1.schema.json;
rewrite ^/saved/([^\.]+)\.json$ /saved/json/$1.json;
```

On the web server, I get messages like the following. 

`2024/04/08 19:14:41 [notice] 52269#0: *11 "^/saved/(.*\.?)context.jsonld$" matches "/saved/core.context.jsonld", client: 127.0.0.1, server: 0.0.0.0, request: "GET /saved/core.context.jsonld HTTP/1.1", host: "localhost"`
`2024/04/08 19:14:41 [notice] 52269#0: *11 rewritten data: "/saved/jsonld/core.context.jsonld", args: "", client: 127.0.0.1, server: 0.0.0.0, request: "GET /saved/core.context.jsonld HTTP/1.1", host: "localhost"`

So, it appears that when calling the `serialize()` method of `RDFGenerator`, it does query the sub-schemas for their own JSON-LD contexts &c. 
 
The issue is that I haven't been generating JSON-LD contexts for schemas apart from `meta.yaml` in my data model, which goes back to my original question here. This was largely based on the LinkML metamodel description [here](https://github.com/linkml/linkml-model/tree/main/linkml_model/model/schema), where you also have this single "meta" file. 

Indeed, as I wrote above, `linkml:units` does not resolve to HTML, much like mine, whereas it does have a valid JSON-LD context: https://linkml.io/linkml-model/linkml_model/jsonld/units.context.jsonld

My Makefile has a near-identical call to gen-project, but this does not generate JSON-LD contexts (and other definitions) for each file, just for the meta-model which is called by gen-project.

Thus, going back to my previous long comment, could you clarify how these are actually generated for each sub-schema pulled in by `meta.yaml`?

**Comment by sneakers-the-rat** [comment]
Ok i tried to debug this for about an hour now and i'm calling it - 

keeping in mind the core of the question is still:

> Thus, going back to my previous long comment, could you clarify how these are actually generated for each sub-schema pulled in by meta.yaml?

which i'm also curious about, here's a bit of info on debugging

--- 

>  I spent a long time trying to catch the urllib errors with setting the logger &c., to no avail.

debugging is made complicated by two things - click and the design of the generator.

you can get a debugger at an exception by doing this:
```shell
python -i $(which gen-rdf) sentinel_cages/sentinel_cages_sampling.yaml -v
```
which should drop you into a python session, and from there you do
```python
import pdb
pdb.pm()
```

which is how i figured out the source of the urllib error here: https://github.com/linkml/linkml/issues/2024#issuecomment-2019052364

setting a breakpoint within `RDFGenerator.end_schema()` doesn't work because the base `Generator` captures stdout in the wrapping `serialize` method - that's gotta change because we should not be using capturing stdout as the means of generating schemas, we should definitely pass strings. 

---

since the url resolution problem is one that's deeper within RDFLib, and it doesn't look like there's a way to prevent it from trying to resolve URIs in the context, I think we need to either a) generate `.context.jsonld` files for each of the imported schemas, which you'd think wouldn't be that hard, but I am having a hell of a time actually doing it. or b) make each schema independent by embedding everything in the imported schema into the current schema (less desirable)

**Comment by druimalban** [comment]
> Ok i tried to debug this for about an hour now and i'm calling it -

Thanks very much for taking the time to go through it with me, it's very kind of you.

> keeping in mind the core of the question is still:
> 
> > Thus, going back to my previous long comment, could you clarify how these are actually generated for each sub-schema pulled in by meta.yaml?
> 
> which i'm also curious about, here's a bit of info on debugging
> 
> > I spent a long time trying to catch the urllib errors with setting the logger &c., to no avail.
> 
> debugging is made complicated by two things - click and the design of the generator.
> 
> you can get a debugger at an exception by doing this:
> 
> ```shell
> python -i $(which gen-rdf) sentinel_cages/sentinel_cages_sampling.yaml -v
> ```
> 
> which should drop you into a python session, and from there you do
> 
> ```python
> import pdb
> pdb.pm()
> ```

Ah, nice! That's very helpful. I have little experience of debugging Python.

> which is how i figured out the source of the urllib error here: [#2024 (comment)](https://github.com/linkml/linkml/issues/2024#issuecomment-2019052364)
> 
> setting a breakpoint within `RDFGenerator.end_schema()` doesn't work because the base `Generator` captures stdout in the wrapping `serialize` method - that's gotta change because we should not be using capturing stdout as the means of generating schemas, we should definitely pass strings.
> 
> since the url resolution problem is one that's deeper within RDFLib, and it doesn't look like there's a way to prevent it from trying to resolve URIs in the context, I think we need to either a) generate `.context.jsonld` files for each of the imported schemas, which you'd think wouldn't be that hard, but I am having a hell of a time actually doing it. or b) make each schema independent by embedding everything in the imported schema into the current schema (less desirable)

Yea, it would be useful to get an idea of best practices when building a data model not dissimilar in structure to the main LinkML meta-model.

**Comment by wwaites** [comment]
> since the url resolution problem is one that's deeper within RDFLib, and it doesn't look like there's a way to prevent it from trying to resolve URIs in the context

We could try to patch RDFLib -- I used to be a maintainer but have not been active for years, and in particular the addition of the `json-ld` parser and serialiser post-dates my involvement. This seems like a bug. Software in general should be tolerant of network resources being unavailable unless they are absolutely required. 

It looks like there is some attempt to make checking (which requires pulling in the context/schema) optional. See https://github.com/RDFLib/rdflib/blob/main/rdflib/plugins/parsers/jsonld.py#L126. It should be perfectly possible to pass in null context data to the `to_rdf` function. There does not seem to be a code path for doing that, and what that might break is unknown...

I suppose we are doing `YAML -> JSON -> RDF` instead of `YAML -> RDF` because in principle a lot of the hard work should already be done for us?

**Comment by sierra-moxon** [comment]
https://github.com/linkml/linkml/issues/2118

**Comment by druimalban** [comment]
This JSON-LD business keeps cropping up:

What I've been doing so far is converting LinkML YAML manifests to TTL. The turtle equivalent is much easier to process, and we eventually want to put the triples in a triple store.

Here is a working YAML manifest - I can use it to validate CSVs &c, and LinkML thinks it's valid:
https://github.com/wwaites/saved_fisdat/blob/main/examples/sentinel_cages/sentinel_cages_sampling.yaml

Let's try conversion to turtle:
```python
from linkml.generators.rdfgen import RDFGenerator
from linkml.utils.schemaloader import SchemaLoader
import urllib.error

print ("LOAD SCHEMA")

target_schema_obj = SchemaLoader ("sentinel_cages_sampling.yaml")
generator = RDFGenerator (schema = target_schema_obj.schema)

print ("GENERATOR")
print (generator)

print ("TRY SERIALISATION")
try:
    generator.serialize()
except urllib.error.HTTPError as e:
    print (f"HTTP error `{e.code}': URL: `{e.url}': reason: ``{e.reason}''")
```

It seems to try and query the following URI: 
`https://linkml.io/linkml-model/meta.jsonld`

Traceback:
```python
Traceback (most recent call last):
  File "/var/db/scratch/scratch/menagerie-mwe/jsonld/run2.py", line 14, in <module>
    generator.serialize()
  File "/var/db/scratch/scratch/fisdat/scratch/lib/python3.12/site-packages/linkml/utils/generator.py", line 332, in serialize
    sub_out = self.end_schema(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/db/scratch/scratch/fisdat/scratch/lib/python3.12/site-packages/linkml/generators/rdfgen.py", line 64, in end_schema
    graph.parse(
  File "/var/db/scratch/scratch/fisdat/scratch/lib/python3.12/site-packages/rdflib/graph.py", line 1492, in parse
    parser.parse(source, self, **args)
  File "/var/db/scratch/scratch/fisdat/scratch/lib/python3.12/site-packages/rdflib/plugins/parsers/jsonld.py", line 119, in parse
    to_rdf(data, conj_sink, base, context_data, version, generalized_rdf)
  File "/var/db/scratch/scratch/fisdat/scratch/lib/python3.12/site-packages/rdflib/plugins/parsers/jsonld.py", line 138, in to_rdf
    return parser.parse(data, context, dataset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/db/scratch/scratch/fisdat/scratch/lib/python3.12/site-packages/rdflib/plugins/parsers/jsonld.py", line 160, in parse
    context.load(local_context, context.base)
  File "/var/db/scratch/scratch/fisdat/scratch/lib/python3.12/site-packages/rdflib/plugins/shared/jsonld/context.py", line 401, in load
    self._prep_sources(base, source, sources, referenced_contexts)
  File "/var/db/scratch/scratch/fisdat/scratch/lib/python3.12/site-packages/rdflib/plugins/shared/jsonld/context.py", line 430, in _prep_sources
    new_ctx = self._fetch_context(
              ^^^^^^^^^^^^^^^^^^^^
  File "/var/db/scratch/scratch/fisdat/scratch/lib/python3.12/site-packages/rdflib/plugins/shared/jsonld/context.py", line 472, in _fetch_context
    source = source_to_json(source_url)  # type: ignore[assignment]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/db/scratch/scratch/fisdat/scratch/lib/python3.12/site-packages/rdflib/plugins/shared/jsonld/util.py", line 44, in source_to_json
    source = create_input_source(source, format="json-ld")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/db/scratch/scratch/fisdat/scratch/lib/python3.12/site-packages/rdflib/parser.py", line 401, in create_input_source
    ) = _create_input_source_from_location(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/db/scratch/scratch/fisdat/scratch/lib/python3.12/site-packages/rdflib/parser.py", line 463, in _create_input_source_from_location
    input_source = URLInputSource(absolute_location, format)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/db/scratch/scratch/fisdat/scratch/lib/python3.12/site-packages/rdflib/parser.py", line 270, in __init__
    response: addinfourl = _urlopen(req)
                           ^^^^^^^^^^^^^
  File "/var/db/scratch/scratch/fisdat/scratch/lib/python3.12/site-packages/rdflib/_networking.py", line 106, in _urlopen
    return urlopen(request)
           ^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 553, in error
    result = self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 745, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 553, in error
    result = self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 745, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

**Comment by druimalban** [comment]
This actually appears to be a breaking change introduced by linkml-runtime v1.7.6. So, I created a bug report.

https://github.com/linkml/linkml/issues/2153

**Comment by nlharris** [comment]
Is the bug sufficiently captured by #2153 that we could close this issue (#1965)?
