### ISSUE TITLE
ValueError: Slot: alt_descriptions - unrecognized element: JsonObj()

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#197]
I am getting this error on all my schemas:

```bash
Traceback (most recent call last):
  File "/Users/cjm/repos/nmdc-schema/venv/bin/gen-json-schema", line 7, in <module>
    from linkml.generators.jsonschemagen import cli
  File "/Users/cjm/repos/nmdc-schema/venv/lib/python3.7/site-packages/linkml/__init__.py", line 4, in <module>
    from linkml_model import linkml_files
  File "/Users/cjm/repos/nmdc-schema/venv/lib/python3.7/site-packages/linkml_model/__init__.py", line 5, in <module>
    from linkml_model.meta import ElementName , SchemaDefinitionName , TypeDefinitionName , SubsetDefinitionName , DefinitionName , \
  File "/Users/cjm/repos/nmdc-schema/venv/lib/python3.7/site-packages/linkml_model/meta.py", line 1068, in <module>
    class PvFormulaOptions(EnumDefinitionImpl):
  File "/Users/cjm/repos/nmdc-schema/venv/lib/python3.7/site-packages/linkml_model/meta.py", line 1073, in PvFormulaOptions
    description="The permissible values are the set of possible codes in the code set")
  File "<string>", line 21, in __init__
  File "/Users/cjm/repos/nmdc-schema/venv/lib/python3.7/site-packages/linkml_model/meta.py", line 990, in __post_init__
    self._normalize_inlined_slot(slot_name="alt_descriptions", slot_type=AltDescription, key_name="source", inlined_as_list=None, keyed=True)
  File "/Users/cjm/repos/nmdc-schema/venv/lib/python3.7/site-packages/linkml/utils/yamlutils.py", line 107, in _normalize_inlined_slot
    raise ValueError(f"Slot: {slot_name} - unrecognized element: {raw_slot_entry}")
ValueError: Slot: alt_descriptions - unrecognized element: JsonObj()
```

to reproduce

```bash
git clone git@github.com:microbiomedata/nmdc-schema.git (or any other)
cd nmdc-schema
. environment.sh
pip install -r requirements.txt
gen-json-schema src/schema/nmdc.yaml 
```

the actual repo is not relevant, and I get the same message with all generators

this may be because I am on Python 3.7.1

**Comment by cmungall** [comment]
It seems this may be restricted to 3.7.1. Works fine with 3.9

**Comment by cmungall** [comment]
on another thread @hsolbrig suggests

`conda install -c anaconda python=3.9`

then `conda config --set pip_interop_enabled True`

**Comment by cmungall** [comment]
Now fixed
