### ISSUE TITLE
Dealing with missing data

### ISSUE THREAD

**Issue by druimalban** [linkml/linkml#1994]
**Is your feature request related to a problem? Please describe.**

Many CSVs, and other data files, have missing data. R typically outputs these as `NA`. NumPy, Pandas &c. also have their own conception of missing data which is near-identical.

It is not clear if LinkML's validation / conversion functionality understands missing data. It certainly does not understand the string "NA".  I certainly can find no documentation about this. This is a very common feature of real data, probably more common than data without missing values, so it seems odd to me that I can find no information about it.

I can remove the NA strings from a given CSV file, and have an empty value for that row, but this conflicts with the notion of a required slot. I think these are two different problems:
1. Presence of the column/slot itself is necessary, called with `required: true` in YAML
2. The column/slot may be required, but the type of the values themselves should understand that not all rows will have a value, at all. They may be missing.

I believe that a CSV file with missing data should validate. The reason for this is that the presence of missing data in itself does not make the data non-compliant, since the assumption is that all other data in the CSV file are of the right type.

**Describe the solution you'd like**

I can also do something like `range: integer | NA_real`, by declaring a distinctive `NA` type, but I don't know if this is an approach which is in tune with LinkML best practice. It seems fairly awkward to me, because it potentially implies a conceptual distinction between data where there are no missing values, and data where there are. I don't think such a distinction is meaningful.

Ideally, the various data-types would themselves have a notion of `NA`. In R, we have the following types of `NA`, because the concept of missing data for e.g. boolean values is distinctly odd:

- `NA_character_`
- `NA_complex_`
- `NA_integer_`
- `NA_real_`

Here, variables which are e.g. `NA_real_` are both missing and of the type real.

I am also not certain about what the implications for dumping/serialisation of any resulting Python objects are.

**How important is this feature?** Select from the options below:
• Important - it's a blocker and can't do work without it

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by cmungall** [comment]
Hi @druimalban!

I have much to say on conventions (or lack of) for missing values in CSV formats. But first let's focus on the internal representation.

I'm not quite following here:

> I can remove the NA strings from a given CSV file, and have an empty value for that row, but this conflicts with the notion of a required slot. I think these are two different problems:

> - Presence of the column/slot itself is necessary, called with required: true in YAML
> - The column/slot may be required, but the type of the values themselves should understand that not all rows will have a value, at all. They may be missing.

I think for many practical scenarios most LinkML modelers would simple relax this to being not `required` and treat `None` the same as missing values, as per normal relational semantics. Of course, there is a whole literature from the early relational modelers about the different meanings of NULL but for most purposes conflating these is fine.

If you really need to have different flavours of NULL then something along your `range: integer | NA_integer` is on the right track. There are even ontologies of missing values that people use here. This would entail using an `any_of`, which ends up complicating your schema. For example, how do you map this to an RDBMS like Postgres? You end up needing to create a special boolean column for every integer column that you want to explicitly record NA for.

Unless there is a real need for an ontology of missing values or need concepts for things like infinity / negative infinity, I would keep it simple - make the slot `required: false` and treat `None` and `NA` as indistinguishable.

I'll return to serialization conventions later but wanted to clarify requirements on the internal representation first

**Comment by sneakers-the-rat** [comment]
I have a whacky idea that might displease everyone. 

So since this is a matter of mapping a particular string pattern onto a python type (as far as the validators/etc. go), and there is no standard string that we would want to hardcode in the metamodel, how about something like this...

```yaml
types:
  NANone:
    pattern: "NA"
    base: None
    repr: None
```

where the implementation would basically be in the loaders, test strings with the pattern, and if they match, then cast to the specified type...

could be cool, seems useful for custom types in general, but i can't tell how common those are. don't have any sense of the tradeoffs but OP is correct there are going to be lots of naturalistic data like this and being able to handle some simple coercions might be nice?

**Comment by amc-corey-cox** [comment]
Hi @druimalban!

Thanks for describing this for us and bringing the idea to our attention. As @cmungall and @sneakers-the-rat both discussed, we wouldn't want to hard-code any particular string as the NA string. For instance, I've seen data with integer values 1-4 and NA represented as 9, 0, or -1. Similarly, strings could be "NA", "N/A", "na", "None", or many other strings.

Generally, I agree with Chris that it is often more practical in LinkML to simply conflate missing and NA to both be none. However, I also see your point that there is a distinction in data between a value being missing (which may be an error that should be dealt with) and a value being "NA" meaning it is a known missing value.

I find @sneakers-the-rat proposal intriguing. Unfortunately, I think it may be a lot to implement for little gain; I'm afraid those who need this special validation wouldn't be aware of it. It begs the question, is our goal to represent real data files with odd coding or to understand that data collection is inherently flawed and will need to be cleaned up and coerced before validation? Idealistically, I prefer the former; practically, I think the latter is more reasonable.

**Comment by druimalban** [comment]
> Hi @druimalban!
> 
> I have much to say on conventions (or lack of) for missing values in CSV formats. But first let's focus on the internal representation.
> 
> I'm not quite following here:
> 
> > I can remove the NA strings from a given CSV file, and have an empty value for that row, but this conflicts with the notion of a required slot. I think these are two different problems:
> 
> > * Presence of the column/slot itself is necessary, called with required: true in YAML
> > * The column/slot may be required, but the type of the values themselves should understand that not all rows will have a value, at all. They may be missing.

OK, I will try and articulate this a bit better:

I have been able to get

**Comment by druimalban** [comment]
> Hi @druimalban!

Hi! Thanks for repyling. I will make a few comments here, this is just the first…

> I'm not quite following here:
> 
> > I can remove the NA strings from a given CSV file, and have an empty value for that row, but this conflicts with the notion of a required slot. I think these are two different problems:
> 
> > * Presence of the column/slot itself is necessary, called with required: true in YAML
> > * The column/slot may be required, but the type of the values themselves should understand that not all rows will have a value, at all. They may be missing.
> 

I'll try and articulate this a bit better. My main use-case of LinkML is to have a parent data model, and then we get folks we're working with to submit data-sets with a schema (which imports types and such from the main data model). The data-sets are validated against the schema, and submitted to a file server.

I have been using the required keyword because it effectively ensures that the column is present in the row. It works well for this.

However, there is a bunch of missing data. The string "NA" isn't important, we can get R or Matlab or whatever the folks submitting the data use to output an empty string or "NULL" or similar. However, NA is the standard string most of these programs appear to output, it's not meaningless.

I was under the impression that you already do quite a lot of coercion and there is parsing for various types, e.g. parse '2' as float. So, it seems to me, like being able to understand the common NA type emitted by statistical programs, would be consistent with the current model.

**Comment by druimalban** [comment]
> I have a whacky idea that might displease everyone.
> 
> So since this is a matter of mapping a particular string pattern onto a python type (as far as the validators/etc. go), and there is no standard string that we would want to hardcode in the metamodel, how about something like this...
> 
> ```yaml
> types:
>   NANone:
>     pattern: "NA"
>     base: "None"
>     repr: "None"
> ```
> 
> (can't recall exactly which is which on `base` and `repr`)
> 
> where the implementation would basically be in the loaders, test strings with the pattern, and if they match, then cast to the specified type...
> 
> could be cool, seems useful for custom types in general, but i can't tell how common those are. don't have any sense of the tradeoffs but OP is correct there are going to be lots of naturalistic data like this and being able to handle some simple coercions might be nice?
> 
> only problem is, for `None` specifically, you actually can't subclass it so it would have to be special cased

That looks about right, thanks. So, here's what I did. This is a test schema+CSV which I've been using for minimum working examples elsewhere (my home directory on this workstation is `/var/db/scratch` and I made a virtualenv in directory scratch, which is a sub-directory of my CWD which is `~/linkml`).

```csv
OS_Identifier,Rough_Lineage,Intro_Dates
"Ken's new system",the original Unics,1969/01
UNIX Time-Sharing System,v1-v7,1961-1975
Wollogong Unix,based on UTS v6,1977/01
2BSD,based on UTS v7,1979/01
SVR4,BSD+SysV features,1988/01
Solaris,"effectively SVR4; Sun collaborated with AT&T",1992/01
```

```yaml
id: http://localhost/unices
name: unices
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types

types:
  NA_None:
    pattern: "NA"
    base: "None"
    repr: "None"
    uri: schema:missing

slots:
  OS_Identifier:
    required: true
    any_of:
      - range: NA_None
      - range: string
  Rough_Lineage:
    required: true
    any_of:
      - range: NA_None
      - range: string
  Intro_Dates:
    required: true
    any_of:
      - range: NA_None
      - range: string

classes:
  Column:
    slots:
      - OS_Identifier
      - Rough_Lineage
      - Intro_Dates

  TableSchema:
    tree_root: true
    attributes:
      columns:
        multivalued: true
        inlined: true
        inlined_as_list: true
        range: Column
```
Validation succeeds ~ `linkml-validate --schema unices.yaml --input-format csv --target-class Column 01-unices-nocommafield.csv`

Serialisation, however fails ~ `linkml-convert --schema unices.yaml --input-format csv --target-class TableSchema --output-format rdf 01-unices-nocommafield.csv`:

```
Traceback (most recent call last):
  File "/var/db/scratch/linkml/scratch/bin/linkml-convert", line 33, in <module>
    sys.exit(load_entry_point('linkml', 'console_scripts', 'linkml-convert')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/db/scratch/linkml/scratch/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/db/scratch/linkml/scratch/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/var/db/scratch/linkml/scratch/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/db/scratch/linkml/scratch/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/db/scratch/linkml/scratch/lib/python3.11/site-packages/linkml/utils/converter.py", line 106, in cli
    python_module = PythonGenerator(schema).compile_module()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/db/scratch/linkml/scratch/lib/python3.11/site-packages/linkml/generators/pythongen.py", line 86, in compile_module
    return compile_python(pycode)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/var/db/scratch/linkml/scratch/lib/python3.11/site-packages/linkml_runtime/utils/compile_python.py", line 47, in compile_python 
    exec(spec, module.__dict__)
  File "test", line 39, in <module>
    `schema':     This is the specification/schema for a given [CSV] file,
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NoneType takes no arguments
```

**Comment by cmungall** [comment]
again, I really think it helps to separate internal representation from serialization/deserialization issues.

If null/None is sufficient for the internal representation (of course, when converting to a pandas dataframe this should be converted to a `pandas.NaN`), then this is just a serialization/deserialization issue.

We can allow for passing in of preferred null-value markers at different levels

- when invoking the python loaders/dumpers directly or via CLI
- via metadata in the schema

When invoking at the python level we can have an option similar to pandas `na_values`:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

The docs say:

_Additional strings to recognize as NA/NaN. If dict passed, specific per-column NA values. By default the following values are interpreted as NaN: “ “, “#N/A”, “#N/A N/A”, “#NA”, “-1.#IND”, “-1.#QNAN”, “-NaN”, “-nan”, “1.#IND”, “1.#QNAN”, “<NA>”, “N/A”, “NA”, “NULL”, “NaN”, “None”, “n/a”, “nan”, “null “._

(this is kind of a crazy list and speaks to a shocking lack of standards...)

Neither `NA` nor any of these should be defaults, this should always be opt-in.

See also:
https://github.com/orgs/linkml/discussions/1996
