### ISSUE TITLE
sqlmodel generator

### ISSUE THREAD

**Issue by manulera** [linkml/linkml#2121]
This has been mentioned previously by @sneakers-the-rat at #1604. 

**Describe the solution you'd like**
[sqlmodel](https://github.com/tiangolo/sqlmodel) is a library that bridges classes from SQLAlchemy and Pydantic. The idea is that with pydantic-like syntax, you define classes that are both pydantic classes (can be used with FastAPI) and SQLAlchemy classes (can work with database).

It would be great if there was a generator 🤖 that generated sqlmodel classes.

**How important is this feature?** Select from the options below:
• Important - it's a blocker and can't do work without it

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Additional context**
I have been using linkml-pydantic in my [FastAPI application](https://github.com/manulera/ShareYourCloning_backend) and I really like it, since I want to make my data model 🎉 FAIR and interoperable 🎉 for people who work with different stacks. The next step for me is to add a database to the website, and it would be ⭐ amazing ⭐ to be able to get sqlmodels from LinkML.

I would be happy to have a go at a PR for the generator if you think this would be a valuable feature. I had a look at the pydantic one and I think I can manage. I would need some back and forth on some things, but given that:

* There is the pydantic generator (syntax is very similar for sqmodels except for relation fields)
* There is the sql generator (I could compare the SQL schema generated from linkml's `gen-sqltables` with that generated by the `sqlmodel` code)

I think I can give it a go.

I have made a [small repository](https://github.com/manulera/linkml_sqlmodel_issue), where i give an example about how a linkml model could be turned into sqlmodel classes. You can run a dummy example and make some changes.

At [the end](https://github.com/manulera/linkml_sqlmodel_issue?tab=readme-ov-file#the-full-solution), I explain why it would also be useful to generate other related classes for http requests and responses. I guess this could be done with LinkML-mapper?

**Comment by sneakers-the-rat** [comment]
I would def use the pydantic generator as the base, and I think you could reuse almost all of the template classes/templates as well. 

I think the things that would need to be changed are
1) primary keys for all models (if they don't already have them, probably adding an `id` field?)
2) relationships between models - `linkml.transformers.relmodel_transformer` has tools for this and is used by the other SQL generating classes, and the result of that transformation seems like p clear dataclasses :)

I wonder if there is any way we could reuse tests from the SQL generators on these? there is going to be some sqlmodel-specific behavior to test but for correctness it would b cool if we could eg. extract out the schema from the sqlite db that the models create and then test all the base SQL stuff with existing tests? idk.

**Comment by manulera** [comment]
Thanks for the advice @sneakers-the-rat, will get to it in the next week.

It's a great idea to compare the output with the SQL output, that should catch a lot of things. And yes, definetely we should add the version somewhere ( I will probably ask about this later).

For now, I have a much more basic question: how do you run the pydantic generator from within the linkml repository directory?

I try to do `python linkml/generators/pydanticgen/pydanticgen.py`, but get the error below:

```
Traceback (most recent call last):
  File "/Users/manu/Documents/OpenSource/linkml/linkml/generators/pydanticgen/pydanticgen.py", line 15, in <module>
    from linkml_runtime.linkml_model.meta import (
  File "/Users/manu/Documents/OpenSource/linkml/.venv/lib/python3.12/site-packages/linkml_runtime/__init__.py", line 2, in <module>
    from linkml_runtime.utils.curienamespace import CurieNamespace
  File "/Users/manu/Documents/OpenSource/linkml/.venv/lib/python3.12/site-packages/linkml_runtime/utils/curienamespace.py", line 3, in <module>
    from rdflib import Namespace, URIRef
  File "/Users/manu/Documents/OpenSource/linkml/.venv/lib/python3.12/site-packages/rdflib/__init__.py", line 47, in <module>
    from importlib import metadata
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/metadata/__init__.py", line 19, in <module>
    from . import _adapters, _meta
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/metadata/_adapters.py", line 5, in <module>
    import email.message
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/email/message.py", line 15, in <module>
    from email import utils
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/email/utils.py", line 29, in <module>
    import socket
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socket.py", line 551, in <module>
    import array
  File "/Users/manu/Documents/OpenSource/linkml/linkml/generators/pydanticgen/array.py", line 17, in <module>
    from linkml_runtime.linkml_model import Element
  File "/Users/manu/Documents/OpenSource/linkml/.venv/lib/python3.12/site-packages/linkml_runtime/linkml_model/__init__.py", line 1, in <module>
    from .types import String, Integer, Boolean, Float, Double, Decimal, Time, Date, Datetime, Uriorcurie, Uri, \
  File "/Users/manu/Documents/OpenSource/linkml/.venv/lib/python3.12/site-packages/linkml_runtime/linkml_model/types.py", line 11, in <module>
    from jsonasobj2 import JsonObj, as_dict
  File "/Users/manu/Documents/OpenSource/linkml/.venv/lib/python3.12/site-packages/jsonasobj2/__init__.py", line 1, in <module>
    from jsonasobj2._jsonobj import JsonObj, as_dict, as_json, as_json_obj, get, items, loads, load, setdefault, \
  File "/Users/manu/Documents/OpenSource/linkml/.venv/lib/python3.12/site-packages/jsonasobj2/_jsonobj.py", line 3, in <module>
    from hbreader import hbread
  File "/Users/manu/Documents/OpenSource/linkml/.venv/lib/python3.12/site-packages/hbreader/__init__.py", line 4, in <module>
    import ssl
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 260, in <module>
    from socket import socket, SOCK_STREAM, create_connection
ImportError: cannot import name 'create_connection' from partially initialized module 'socket' (most likely due to a circular import) (/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socket.py)
```

**Comment by cmungall** [comment]
> relationships between models - linkml.transformers.relmodel_transformer has tools for this and is used by the other SQL generating classes, and the result of that transformation seems like p clear dataclasses :)

This step is key - but to clarify, the output is not dataclasses, the model transformers are independent of pydantic vs dataclasses, they produce transformed *linkml models*. 

Many databases do not yet supports lists/sets/arrays as native types, and even when they do they may not be directly supported (e.g. https://github.com/tiangolo/sqlmodel/issues/178) so it is important to allow for transformation to a relmodel as a composable step

**Comment by sneakers-the-rat** [comment]
right yes I meant dataclasses as in these puppies not like `pythongen` dataclasses: https://github.com/linkml/linkml/blob/db13b572d4b89c0c54db44819c4937c41f29ad8d/linkml/transformers/relmodel_transformer.py#L31-L133

@manulera typically you can't just execute python modules within a package just as files since they expect the `__init__.py` files in the containing and parent modules to be executed/imported as well, and that looks like a fun little circular import. to execute modules within packages generally you do `python -m package.module.submodule` so in this case `python -m linkml.generators.pydanticgen.pydanticgen` but linkml also provides a [cli entrypoint](https://github.com/linkml/linkml/blob/db13b572d4b89c0c54db44819c4937c41f29ad8d/pyproject.toml#L71) `gen-pydantic` (make sure the package is installed in your venv first `python -m pip install -e .` )

**Comment by manulera** [comment]
Thanks @sneakers-the-rat for the module syntax!

Somehow when I tried last I could not find `gen-pydantic` in the path. Anyway, I installed it again now and it worked, I must have done something wrong last time.

**Comment by nlharris** [comment]
Can this be closed?

**Comment by sneakers-the-rat** [comment]
Hopefully the difficulty with running the generator has been resolved, but i think the original issue for making SQLModel generator is still worth keeping - i plan on doing it at some point unless someone beats me to it ;)
