### ISSUE TITLE
gen-doc (1.7.10) fails with obscure message

### ISSUE THREAD

**Issue by joshmoore** [linkml/linkml#2126]
**Describe the bug**

```
$ gen-doc X -d Y
AttributeError: type object 'NoneType' has no attribute 'class_name'
```

adding `-vvv --stacktrace --log_level=DEBUG` I see:

```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/ome-ld/bin/gen-doc", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/ome-ld/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/ome-ld/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/ome-ld/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/ome-ld/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/ome-ld/lib/python3.12/site-packages/linkml/generators/docgen.py", line 978, in cli
    print(gen.serialize())
          ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/ome-ld/lib/python3.12/site-packages/linkml/generators/docgen.py", line 216, in serialize
    out_str = template.render(gen=self, element=c, schemaview=sv, **template_vars)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/ome-ld/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/ome-ld/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/ome-ld/lib/python3.12/site-packages/linkml/generators/docgen/class.md.jinja2", line 54, in top-level template code
    {% include "class_diagram.md.jinja2" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/ome-ld/lib/python3.12/site-packages/linkml/generators/docgen/class_diagram.md.jinja2", line 25, in top-level template code
    {{ gen.name(schemaview.get_element(s)) }} <|-- {{ gen.name(element) }}
^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/ome-ld/lib/python3.12/site-packages/linkml/generators/docgen.py", line 344, in name
    if type(element).class_name == "slot_definition":
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'NoneType' has no attribute 'class_name'
```

**To reproduce**
I have not yet tracked down which file is causing this, but I'm opening the bug now with the hope that someone else has seen this before. More info when I found the problem.

**Expected behavior**
Just that the docs are generated.

**About your computer (if applicable, please complete the following information):**
 - OS: [e.g. iOS] OSX

**Additional context**

**Comment by sierra-moxon** [comment]
Hi @joshmoore - I am able to use `gen-doc` to build and serve documentation with linkml 1.7.x.
apologies, I can't remember the location of your GH repo for this schema - can you point me at it and I will give it a whirl?

**Comment by joshmoore** [comment]
Hi @sierra-moxon, I'm developing new (well, code-generating new) schemas and so they're a mess. In that sense, this isn't high-priority but perhaps can point to a necessary assertion check somewhere. (Has there been a discussion about adding a call to type checking via `mypy`?)

I can add to the debugging of the above that `linkml-validate` on the above passed but `linkml-validate --legacy-mode -s` did **not**!

**Comment by sherwoodf** [comment]
Hi! I'm getting the exact same error & stack trace when running the same command when running on a small portion of the schema i'm working on. Pydantic models are correctly generated, gen-doc works, and so are mermaid diagrams.

Here's a link to my pull request with the schema: 
https://github.com/BioImage-Archive/bia-integrator/pull/111/files#diff-5338d5bf22d574aee238a8d8641ea84a2b10573c9600073f1be75b4e32edc1cf

**Comment by sujaypatil96** [comment]
Thank you for reporting this and sharing links to your schemas @joshmoore and @sherwoodf! I will try to reproduce this on my end and address your issue.

**Comment by sujaypatil96** [comment]
@sherwoodf i see only downstream/generated LinkML artifacts here: https://github.com/BioImage-Archive/bia-integrator/tree/shared_models/bia-shared-datamodels, where can I find the actual YAML file?

**Comment by sujaypatil96** [comment]
@joshmoore linkml v1.7.8 is being used to power the documentation of a well known and widely utilized schema called the NMDC schema here: https://microbiomedata.github.io/nmdc-schema/. I'm not seeing any problems building the documentation. 

Also just noting the typo in the command that you put in, `gen-docs` --> `gen-doc`

**Comment by sherwoodf** [comment]
Ah sorry, added some new commits which removed those files. Here is a link to the commit: https://github.com/BioImage-Archive/bia-integrator/pull/111/commits/fda3a4e060eb6702c01569e0ea13bd9a8cfc37c7#diff-f23231bfb951a3708c0117691413c6b34dbf3c648dea77d282e21569916a1446

**Comment by joshmoore** [comment]
> Also just noting the typo in the command that you put in, `gen-docs` --> `gen-doc`

:+1: fixed.



> @joshmoore linkml v1.7.8 is being used to power the documentation of a well known and widely utilized schema called the NMDC schema here: https://microbiomedata.github.io/nmdc-schema/. I'm not seeing any problems building the documentation.

Oh, of course. I don't doubt that it works, and I've used it successfully elsewhere. But this is essentially a NullPointerException deep within the LinkML code base which is worrisome.

**Comment by cramatt** [comment]
FWIW - I encountered this same error message and fixed it by adding `default_range: string` to my schema. Seems maybe related to an issue when using `range` types but missing `default_range: string` definition?

**Comment by joshmoore** [comment]
Thanks, @cramatt. Certainly possible, but of course at this point this has significantly timed out. I have no objection to it being closed.
