### ISSUE TITLE
linkml-lint and config file

### ISSUE THREAD

**Issue by ddooley** [linkml/linkml#2148]
**Describe the bug**
Not sure if this is the right repo issue to report this but I try running linkml-lint version 1.7.10 with the given example in: https://linkml.io/linkml/schemas/linter.html#configuration , namely

`linkml-lint --config validation_config.yaml schema.yaml`

With validation_config.yaml = 

```
extends: recommended
rules:
  standard_naming:
    level: disabled
```
But it is erroring out with:
```
Traceback (most recent call last):
  File "/Applications/anaconda3/bin/linkml-lint", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Applications/anaconda3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/anaconda3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Applications/anaconda3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/anaconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/anaconda3/lib/python3.11/site-packages/linkml/linter/cli.py", line 118, in main
    linter = Linter(config_dict)
             ^^^^^^^^^^^^^^^^^^^
  File "/Applications/anaconda3/lib/python3.11/site-packages/linkml/linter/linter.py", line 72, in __init__
    if config.get("extends") == ExtendableConfigs.recommended.text:
       ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```
On a Mac M3, and hoping I've installed linkml correctly.

**Comment by ddooley** [comment]
Also I was wondering if the very same "--config validation_config.yaml" could be used with linkml-validate to drop ERROR reporting of non-standard class, slot and enum names?

**Comment by ddooley** [comment]
This can be closed.  My bad. Accidentally the validation_config.yaml was zero length so not really an error that needs to be trapped.
