### ISSUE TITLE
Markdowngen in linkml throws error via linkml-model (I think).

### ISSUE THREAD

**Issue by hrshdhgd** [linkml/linkml#231]
I was developing a small part of `markdowngen` for `enums` in linkml (v0.07) and ran code to test things out which worked fine. On running the same code for `markdowngen` today, I am getting an error.

The code I was trying to run:
```
python -m linkml.generators.markdowngen traits.yaml -d test_folder
```
The `traits.yaml` file can be found [here](https://github.com/Knowledge-Graph-Hub/kg-microbe/blob/master/schemas/trait_condensed.yaml).

The error I received:

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/linkml-0.1.1.dev2-py3.9.egg/linkml/generators/markdowngen.py", line 573, in <module>
    cli()
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/click-8.0.1-py3.9.egg/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/click-8.0.1-py3.9.egg/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/click-8.0.1-py3.9.egg/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/click-8.0.1-py3.9.egg/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/linkml-0.1.1.dev2-py3.9.egg/linkml/generators/markdowngen.py", line 568, in cli
    MarkdownGenerator(yamlfile, no_types_dir=notypesdir, warn_on_exist=warnonexist, **kwargs)\
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/linkml-0.1.1.dev2-py3.9.egg/linkml/generators/markdowngen.py", line 25, in __init__
    super().__init__(schema, **kwargs)
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/linkml-0.1.1.dev2-py3.9.egg/linkml/utils/generator.py", line 89, in __init__
    loader = SchemaLoader(schema, self.base_dir, useuris=useuris, importmap=importmap, logger=self.logger,
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/linkml-0.1.1.dev2-py3.9.egg/linkml/utils/schemaloader.py", line 51, in __init__
    self.schema = load_raw_schema(data, base_dir=base_dir, merge_modules=mergeimports,
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/linkml-0.1.1.dev2-py3.9.egg/linkml/utils/rawloader.py", line 78, in load_raw_schema
    return load_raw_schema(f, fname, time.ctime(os.path.getmtime(fname)), os.path.getsize(fname), base_dir,
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/linkml-0.1.1.dev2-py3.9.egg/linkml/utils/rawloader.py", line 151, in load_raw_schema
    for sname, sdef in {k: SchemaDefinition(name=k, **as_dict(v)) for k, v in schemadefs.items()}.items():
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/linkml-0.1.1.dev2-py3.9.egg/linkml/utils/rawloader.py", line 151, in <dictcomp>
    for sname, sdef in {k: SchemaDefinition(name=k, **as_dict(v)) for k, v in schemadefs.items()}.items():
  File "<string>", line 49, in __init__
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/linkml_runtime-1.0.8-py3.9.egg/linkml_runtime/linkml_model/meta.py", line 316, in __post_init__
    self._normalize_inlined_as_dict(slot_name="slots", slot_type=SlotDefinition, key_name="name", keyed=True)
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/linkml_runtime-1.0.8-py3.9.egg/linkml_runtime/utils/yamlutils.py", line 97, in _normalize_inlined_as_dict
    self._normalize_inlined(slot_name, slot_type, key_name, keyed, False)
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/linkml_runtime-1.0.8-py3.9.egg/linkml_runtime/utils/yamlutils.py", line 193, in _normalize_inlined
    form_1({k: v})
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/linkml_runtime-1.0.8-py3.9.egg/linkml_runtime/utils/yamlutils.py", line 146, in form_1
    order_up(key, slot_type(**as_dict(raw_obj)))
  File "<string>", line 67, in __init__
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/linkml_runtime-1.0.8-py3.9.egg/linkml_runtime/linkml_model/meta.py", line 650, in __post_init__
    super().__post_init__(**kwargs)
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/linkml_runtime-1.0.8-py3.9.egg/linkml_runtime/linkml_model/meta.py", line 462, in __post_init__
    super().__post_init__(**kwargs)
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/linkml_runtime-1.0.8-py3.9.egg/linkml_runtime/linkml_model/meta.py", line 185, in __post_init__
    self.examples = [v if isinstance(v, Example) else Example(**v) for v in self.examples]
  File "/opt/anaconda3/envs/kg-microbe-2/lib/python3.9/site-packages/linkml_runtime-1.0.8-py3.9.egg/linkml_runtime/linkml_model/meta.py", line 185, in <listcomp>
    self.examples = [v if isinstance(v, Example) else Example(**v) for v in self.examples]
TypeError: linkml_runtime.linkml_model.meta.Example() argument after ** must be a mapping, not JsonObj
```

I was wondering what if anything has changed that I need to accommodate for in my project.

**Comment by cmungall** [comment]
are you using the latest version?

I see `linkml-0.1.1.` in the above

we are on 1.0.0

**Comment by hrshdhgd** [comment]
I updated linkml to 1.0.0, still get the same error.

<img width="297" alt="Screen Shot 2021-06-15 at 9 27 33 AM" src="https://user-images.githubusercontent.com/5247075/122070929-f781f600-cdbb-11eb-8850-9b210bb01a0c.png">

**Comment by hrshdhgd** [comment]
Hello @hsolbrig ! I'm just using the command line as shown above. For this particular project I have linkml installed through KGX. Could you please elaborate where do I look for the 'list of imports'? Sorry, I do not follow.

**Comment by hsolbrig** [comment]
Not sure the environment you are using, but either `pip list` or `pipenv run pip list` depending on the setting.   Let me know if a short zoom session would be helpful

**Comment by hrshdhgd** [comment]
Aah! Thank you for the clarification. I'm using Anaconda. Here's the list.

```
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
antlr4-python3-runtime    4.9.2                    pypi_0    pypi
argparse                  1.4.0                    pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
babel                     2.9.1                    pypi_0    pypi
bmt                       0.6.0                    pypi_0    pypi
bottle                    0.12.19                  pypi_0    pypi
ca-certificates           2021.5.25            hecd8cb5_1  
cachetools                4.2.2                    pypi_0    pypi
certifi                   2021.5.30        py39hecd8cb5_0  
cfgraph                   0.2.1                    pypi_0    pypi
chardet                   4.0.0                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
decorator                 5.0.9                    pypi_0    pypi
deprecated                1.2.12                   pypi_0    pypi
deprecation               2.1.0                    pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
frozendict                2.0.2                    pypi_0    pypi
greenlet                  1.1.0                    pypi_0    pypi
hbreader                  0.9.1                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
ijson                     3.1.4                    pypi_0    pypi
imagesize                 1.2.0                    pypi_0    pypi
isodate                   0.6.0                    pypi_0    pypi
jinja2                    3.0.1                    pypi_0    pypi
joblib                    1.0.1                    pypi_0    pypi
jsonasobj2                1.0.4                    pypi_0    pypi
jsonlines                 2.0.0                    pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jsonstreams               0.6.0                    pypi_0    pypi
kgx                       1.1.0                    pypi_0    pypi
libcxx                    10.0.0                        1  
libffi                    3.3                  hb1e8313_2  
linkml                    1.0.0                    pypi_0    pypi
linkml-model              1.0.0                    pypi_0    pypi
linkml-runtime            1.0.10                   pypi_0    pypi
lxml                      4.6.3                    pypi_0    pypi
markdown-it-py            1.1.0                    pypi_0    pypi
markupsafe                2.0.1                    pypi_0    pypi
matplotlib                3.4.2                    pypi_0    pypi
mdit-py-plugins           0.2.8                    pypi_0    pypi
ncurses                   6.2                  h0a44026_1  
neo4jrestclient           2.1.1                    pypi_0    pypi
networkx                  2.6rc1                   pypi_0    pypi
nltk                      3.6.2                    pypi_0    pypi
numpy                     1.21.0rc1                pypi_0    pypi
oger                      1.5                      pypi_0    pypi
openssl                   1.1.1k               h9ed2024_0  
packaging                 20.9                     pypi_0    pypi
pandas                    1.2.4                    pypi_0    pypi
parameterized             0.8.1                    pypi_0    pypi
parse                     1.19.0                   pypi_0    pypi
pbr                       5.6.0                    pypi_0    pypi
pip                       21.1.1           py39hecd8cb5_0  
prefixcommons             0.1.9                    pypi_0    pypi
prologterms               0.0.6                    pypi_0    pypi
pygments                  2.9.0                    pypi_0    pypi
pyjsg                     0.11.6                   pypi_0    pypi
pyld                      2.0.3                    pypi_0    pypi
pyparsing                 3.0.0b2                  pypi_0    pypi
pyrsistent                0.17.3                   pypi_0    pypi
pyshex                    0.7.20                   pypi_0    pypi
pyshexc                   0.8.3                    pypi_0    pypi
pytest                    6.2.4                    pypi_0    pypi
python                    3.9.5                h88f2d9e_3  
python-dateutil           2.8.1                    pypi_0    pypi
python-graphviz           0.16                     pypi_0    pypi
pytz                      2021.1                   pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
rdflib                    5.0.0                    pypi_0    pypi
rdflib-jsonld             0.5.0                    pypi_0    pypi
rdflib-pyld-compat        0.1.0                    pypi_0    pypi
rdflib-pyldmod-compat     0.1.1                    pypi_0    pypi
readline                  8.1                  h9ed2024_0  
recommonmark              0.7.1                    pypi_0    pypi
regex                     2021.4.4                 pypi_0    pypi
requests                  2.25.1                   pypi_0    pypi
scipy                     1.6.3                    pypi_0    pypi
setuptools                52.0.0           py39hecd8cb5_0  
shexjsg                   0.7.1                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
snowballstemmer           2.1.0                    pypi_0    pypi
sparqlslurper             0.4.1                    pypi_0    pypi
sparqlwrapper             1.8.5                    pypi_0    pypi
sphinx                    3.5.4                    pypi_0    pypi
sphinx-rtd-theme          0.5.2                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlalchemy                1.4.18                   pypi_0    pypi
sqlite                    3.35.4               hce871da_0  
testfixtures              6.17.1                   pypi_0    pypi
tk                        8.6.10               hb0a8c7a_0  
tqdm                      4.61.0                   pypi_0    pypi
tzdata                    2020f                h52ac0ba_0  
urllib3                   1.26.5                   pypi_0    pypi
validators                0.18.2                   pypi_0    pypi
watchdog                  2.1.2                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.5                h1de35cc_0  
zlib                      1.2.11               h1de35cc_3  
```

**Comment by hsolbrig** [comment]
Hmmm.... everything there looks OK.  What is the input file that you are feeding to the markdown generator?

**Comment by hrshdhgd** [comment]
https://github.com/Knowledge-Graph-Hub/kg-microbe/blob/master/schemas/trait_condensed.yaml

**Comment by hsolbrig** [comment]
`s/value: /- value:/`

Separate issue filed above to actually fix it
