### ISSUE TITLE
Error in python 3.13 importing 're' from 'typing' package

### ISSUE THREAD

**Issue by HendrikBorgelt** [linkml/linkml#2378]
**Describe the bug**
A clear and concise description of what the bug is (including the error message that is printed, if any)

I get an import error when trying to execute `linkml-convert --help` in a python3.13 venv.

The error states:
```
(venv) .\linkml-tutorial-py313>linkml-convert --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File ".\linkml-tutorial-py313\venv\Scripts\linkml.exe\__main__.py", line 4, in <module>
    from linkml.cli.main import linkml
  File ".\linkml-tutorial-py313\venv\Lib\site-packages\linkml\__init__.py", line 4, in <module>
    from linkml_runtime.linkml_model import linkml_files
  File ".\linkml-tutorial-py313\venv\Lib\site-packages\linkml_runtime\__init__.py", line 3, in <module>
    from linkml_runtime.utils.schemaview import SchemaView
  File ".\linkml-tutorial-py313\venv\Lib\site-packages\linkml_runtime\utils\schemaview.py", line 17, in <module>
    from linkml_runtime.linkml_model.meta import *
  File ".\linkml-tutorial-py313\venv\Lib\site-packages\linkml_runtime\linkml_model\__init__.py", line 1, in <module>
    from .types import String, Integer, Boolean, Float, Double, Decimal, Time, Date, Datetime, Uriorcurie, Uri, \
        Ncname, Objectidentifier, Nodeidentifier
  File ".\linkml-tutorial-py313\venv\Lib\site-packages\linkml_runtime\linkml_model\types.py", line 15, in <module>
    from linkml_runtime.utils.slot import Slot
  File ".\linkml-tutorial-py313\venv\Lib\site-packages\linkml_runtime\utils\slot.py", line 2, in <module>
    from typing import Type, List, Optional, Any, re
ImportError: cannot import name 're' from 'typing' (C:\Users\smhhborg\AppData\Local\Programs\Python\Python313\Lib\typing.py)
```

I shortened the path from:
` D:\Users\smhhborg(D_Laufwerk)\Documents\GitHub\LinkML-Tutorial-for-Python-Scripting\`
to
`.\`
for better readability.

**Version of LinkML you are using**
The most recent available via `pip install linkml`.

I hope this helps: 
```
linkml-tutorial-py313>pip install linkml
Collecting linkml
  Downloading linkml-1.8.4-py3-none-any.whl.metadata (3.9 kB)
...
```

**Comment by dalito** [comment]
LinkML is not yet tested against Python 3.13, see https://github.com/linkml/linkml/blob/main/.github/workflows/main.yaml

Could your colleague switch to Python 3.12 until #2358 lands?

**Comment by HendrikBorgelt** [comment]
Sorry misunderstood the other issue. 

yes, i send a fix to the respective colleague on how to use py3.11 in my case.

**Comment by asadow** [comment]
Just an FYI, [doc's](https://linkml.io/linkml/intro/install.html) instruct to use latest python

**Comment by caufieldjh** [comment]
Reopening - if python 3.13 isn't supported then this needs to be explicit in the docs and packaging configs, or downstream packages updating to 3.13 (e.g., oaklib, sssom-py, ontogpt) will break

**Comment by caufieldjh** [comment]
Once https://github.com/linkml/linkml/pull/2358 and https://github.com/linkml/linkml-runtime/pull/345 are complete then that won't be as much of an issue, of course

**Comment by jamesamcl** [comment]
This is the cause of https://github.com/monarch-initiative/pheval/issues/369

**Comment by caufieldjh** [comment]
🎉
