### ISSUE TITLE
Need a pure CURIE type

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#258]
The types.yaml have urirocurie and uri types, but no curie

**Comment by sierra-moxon** [comment]
We need to decide if we fail validation if a colon is missing, or try to "fix" this for the user and pre-pend the base prefix when a colon does not exist. 
- do we want to fail on HTTP[s]:? vs. https://  
- is it expandable?  
- is it valid in bioregistry? 

We need to match the curie specification directly so we don't make our own rules and confuse people.

**Comment by cmungall** [comment]
Note that we already have validation on the uriorcurie type, but it is less strict than the standard.

```
>>> from linkml_runtime.utils.metamodelcore import URIorCURIE
>>> URIorCURIE("x")
'x'
>>> URIorCURIE("foo bar:1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oaklib-OeQZizwE-py3.9/lib/python3.9/site-packages/linkml_runtime/utils/metamodelcore.py", line 100, in __init__
    raise ValueError(f"{v} is not a valid URI or CURIE")
ValueError: foo bar:1 is not a valid URI or CURIE
```

we should use the same is_curie code, but we should not be any more strict than is mandated by w3c specs, i.e no bioregistry lookups (many people use linkml for non-bio use cases)

**Comment by Silvanoc** [comment]
> We need to decide if we fail validation if a colon is missing, or try to "fix" this for the user and pre-pend the base prefix when a colon does not exist.

> Note that we already have validation on the uriorcurie type, but it is less strict than the standard.

According the [syntax in the W3C specification](https://www.w3.org/TR/curie/#s_syntax), both the prefix and the colon are optional. According the corresponding specs, a string without a colon is at the same time a valid _CURIE_ and a valid _relative URI_!

### CURIEs vs compact URIs

I wonder if LinkML is rather interested in supporting _[compact URIs](https://www.w3.org/TR/json-ld11/#compact-iris) (as specified in the JSON-LD v1.1 specification)_ than _[CURIEs](https://www.w3.org/TR/curie) (as specified in the CURIE spec)_ and mix them up. What is easy, because they are very similar, but not the same.

Two very important differences (because they help differentiate _URIs_ and what LinkML calls _CURIEs_) are:

1.  that _compact URIs_ MUST have a prefix and the prefix MUST be listed in the JSON-LD context
2. that disambiguation is (more or less) [clearly specified](https://www.w3.org/TR/json-ld11/#compact-iris)

Is important to notice that:

1. _compact URIs_ "shadows" _URIs_ (valid _URIs_ being interpreted as _compat URIs_ instead) in the extremely rare case of an _URI_ with the same _scheme_ as a _prefix_ and with [a _path_](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax) that is also a valid _compact URI_ _suffix_ (for example, something like `iot:device` is at the same time a valid _compact URI_ when `iot` is in `prefixes` and a valid _URI_)
2. the _compact URI_ spec doesn't clarify what is the syntax of the _suffix_ (could it contain a colon or a slash?)

Therefore IMO "renaming" (changing documentation and code accordingly) from _CURIE_ to _compact URI_ (according the JSON-LD specification) would be the solution with the smallest _URI_ "shadowing" keeping backwards compatibility.

---

### Sticking to CURIEs

#### Disambiguation of CURIEs

As mentioned in [this comment in issue 1400](https://github.com/linkml/linkml/issues/1400#issuecomment-1717880004), the only way to avoid the ambiguity between _URIs_ and _CURIEs_ is using characters not allowed in a _URI_ (like it's [recommended in the _CURIE_ spec](https://www.w3.org/TR/curie/#sec_2.2.)). But I assume that the LinkML wouldn't like this approach.

Any approach accepting both "unsafe" _CURIEs_ and URIs has a bigger or smaller ambiguity.

#### Migration from "unsafe" CURIEs to "safe" CURIEs

If sticking to _CURIEs_ instead of _compact URIs_, I see a possibility for a grace migration from "unsafe" to "safe" CURIEs:
Perhaps adding support for safe-CURIEs without rejection of "unsafe" CURIEs (perhaps only a warning) would help migrate to use of

**Comment by turbomam** [comment]
removing Harold as the assignee

I appreciate @Silvanoc's analysis and proposals

A common cause of `linkml-run-examples` failing in nmdc-schema is a missing prefix. I would prefer clearer guidance on this (asserting a base prefix somewhere?) and warnings instead of script termination.

Who should be the assignee? I can help.

**Comment by Silvanoc** [comment]
I'm absent the upcoming two weeks. If it can wait until I'm back, I can have a look at it. I've snoozed the notification until I'm back so that I don't forget it.

**Comment by nlharris** [comment]
Is this done?

**Comment by cmungall** [comment]
I think there are multiple duplicate issues here but we need to keep one

**Comment by nlharris** [comment]
Which issue(s) duplicate this one?

**Comment by sujaypatil96** [comment]
PR with fix: https://github.com/linkml/linkml-model/pull/221

CC: @ialarmedalien @cmungall

**Comment by nlharris** [comment]
Looks like the PR still needs a bunch of testing before it can be merged.

**Comment by nlharris** [comment]
> Which issue(s) duplicate this one?

#272, maybe?
