### ISSUE TITLE
markdowngen: Mysterious "ValueError: Unrecognized prefix" error with latest version of libraries

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#537]
Seeing occasional failures, e.g. in https://github.com/linkml/linkml/runs/4602066574?check_suite_focus=true

often these are in markdowngen, e.g.

```
======================================================================
ERROR: test_issue_179 (tests.test_issues.test_issue_179.Issue179TestCase)
Make sure that inheritence isn't implied by reference slots
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/linkml/linkml/tests/test_issues/test_issue_179.py", line 13, in test_issue_179
    env.generate_directory('issue179',
  File "/home/runner/work/linkml/linkml/tests/utils/test_environment.py", line 185, in generate_directory
    generator(temp_output_directory)
  File "/home/runner/work/linkml/linkml/tests/test_issues/test_issue_179.py", line 14, in <lambda>
    lambda d: MarkdownGenerator(env.input_path('issue_179.yaml')).serialize(directory=d))
  File "/home/runner/work/linkml/linkml/linkml/utils/generator.py", line 128, in serialize
    self.visit_slot(self.aliased_slot_name(slot), slot)
  File "/home/runner/work/linkml/linkml/linkml/generators/markdowngen.py", line 227, in visit_slot
    slot_curie = self.namespaces.uri_or_curie_for(self.namespaces._base, underscore(slot.name))
  File "/home/runner/.local/share/virtualenvs/linkml-GXYf-q4E/lib/python3.8/site-packages/linkml_runtime/utils/namespaces.py", line 195, in uri_or_curie_for
    raise ValueError(f"Unrecognized prefix: {prefix}")
ValueError: Unrecognized prefix: http://example.org/sample/example1/
```

the code is unchanged, it seems to be caused by using a certain combo of rdflib libraries. I can't replicate this error in my local environment

also in other places:

```
======================================================================
ERROR: test_sparqlgen (tests.test_generators.test_sparqlgen.SparqlGeneratorTestCase)
Generate java classes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/linkml/linkml/tests/test_generators/test_sparqlgen.py", line 18, in test_sparqlgen
    gen = SparqlGenerator(SCHEMA)
  File "/home/runner/work/linkml/linkml/linkml/generators/sparqlgen.py", line 144, in __init__
    materialize_schema(schemaview)
  File "/home/runner/work/linkml/linkml/linkml/generators/sparqlgen.py", line 110, in materialize_schema
    schema.prefixes['rdf'] = Prefix('rdf', str(RDF.uri))
  File "/home/runner/.local/share/virtualenvs/linkml-GXYf-q4E/lib/python3.8/site-packages/rdflib/namespace/__init__.py", line 205, in __getattr__
    return cls.__getitem__(name)
  File "/home/runner/.local/share/virtualenvs/linkml-GXYf-q4E/lib/python3.8/site-packages/rdflib/namespace/__init__.py", line 196, in __getitem__
    raise AttributeError(f"term '{name}' not in namespace '{cls._NS}'")
AttributeError: term 'uri' not in namespace 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
```

This PR has a null change, and introduces the error:

 * #536 

We did not have this before, so some upstream library has changed

also reported here:

 * #535 
 * https://github.com/linkml/linkml-runtime/issues/96

**Comment by cmungall** [comment]
I suspect this line in namespaces.py is the problem:

```python
if isinstance(prefix, URIRef) or ':/' in prefix:
```

@hsolbrig I recall you saying the behavior of `in` on `URIRef` changed in rdflib6....
