### ISSUE TITLE
when using 'attributes' instead of 'slots' on a class gen-rdf attempts to create duplicate __slot_name values?

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#713]
**Describe the bug**
when using 'attributes' instead of 'slots' on a class gen-rdf attempts to create duplicate __slot_name values?
when using the work-around with attributes, no prefix errors are generated, but running linkml convert using the command line, the prefix issue from #439 still persists.

**To Reproduce**
Note: changing the simple schema to use "slots" collection instead of "attributes" allows this test to pass successfully.  
```
python -m unittest tests/test_generators/test_rdfgen.py
E
======================================================================
ERROR: test_rdfgen (tests.test_generators.test_rdfgen.RDFTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/victoria/Documents/GitHub/linkml/tests/test_generators/test_rdfgen.py", line 23, in test_rdfgen
    rdf = RDFGenerator(SCHEMA, mergeimports=True).serialize()
  File "/Users/victoria/Documents/GitHub/linkml/linkml/utils/generator.py", line 136, in serialize
    self.end_schema(**kwargs)
  File "/Users/victoria/Documents/GitHub/linkml/linkml/generators/rdfgen.py", line 41, in end_schema
    jsonld_str = gen.serialize(context=context)
  File "/Users/victoria/Documents/GitHub/linkml/linkml/utils/generator.py", line 136, in serialize
    self.end_schema(**kwargs)
  File "/Users/victoria/Documents/GitHub/linkml/linkml/generators/jsonldgen.py", line 114, in end_schema
    add_prefixes = ContextGenerator(self.original_schema, model=False, metadata=False).serialize()
  File "/Users/victoria/Documents/GitHub/linkml/linkml/generators/jsonldcontextgen.py", line 38, in __init__
    super().__init__(schema, **kwargs)
  File "/Users/victoria/Documents/GitHub/linkml/linkml/utils/generator.py", line 96, in __init__
    loader.resolve()
  File "/Users/victoria/Documents/GitHub/linkml/linkml/utils/schemaloader.py", line 132, in resolve
    self.raise_value_error(f'Class: "{cls.name}" attribute "{attribute.name}" - '
  File "/Users/victoria/Documents/GitHub/linkml/linkml/utils/schemaloader.py", line 780, in raise_value_error
    SchemaLoader.raise_value_errors(error, loc_str)
  File "/Users/victoria/Documents/GitHub/linkml/linkml/utils/schemaloader.py", line 788, in raise_value_errors
    raise ValueError(f'{TypedNode.yaml_loc(loc_str, suffix="")} {error}')
ValueError:  Class: "Person" attribute "id" - mangled name: person__id already exists
----------------------------------------------------------------------
Ran 1 test in 1.261s
FAILED (errors=1)
```
**Expected behavior**
python -m unittest tests/test_generators/test_rdfgen.py should work without changing attributes to slots. otherwise, original prefix errors should persist, so that we can get to the root of the issue in #429 

**Additional context**
@victoriasoesanto ran across this issue.
biolink-model does not make heavy use of attributes convention, rather uses slots so it may not be surfacing this issue.

**Comment by sierra-moxon** [comment]
closing as complete
