### ISSUE TITLE
resolve difference between rdfdumper and rdflibdumper: linkml-convert json-ld bug

### ISSUE THREAD

**Issue by adlerfaulkner** [linkml/linkml#805]
**Describe the bug**
When attempting to use `linkml-convert` with `-t json-ld` I get the following error:

```
Traceback (most recent call last):
  File "/Users/adlerfaulkner/skl/venv/bin/linkml-convert", line 8, in <module>
    sys.exit(cli())
  File "/Users/adlerfaulkner/skl/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/adlerfaulkner/skl/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/adlerfaulkner/skl/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/adlerfaulkner/skl/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/adlerfaulkner/skl/venv/lib/python3.9/site-packages/linkml/utils/converter.py", line 136, in cli
    print(dumper.dumps(obj, **outargs))
TypeError: dumps() got an unexpected keyword argument 'contexts'
```

**To Reproduce**
Using these files from the tutorial:

personinfo.yaml
```
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

classes:
  Person:
    attributes:
      id:
      full_name:
      aliases:
      phone:
      age:
```
person.yaml
```
id: ORCID:1234
full_name: Clark Kent
age: 32
phone: 555-555-5555
```

Run `linkml-convert -s personinfo.yaml data.yaml -t json-ld`

**Expected behavior**
I should not get an error and should see jsonld printed in my terminal window

**Versions:**
 - OS: macOS 12.3.1
 - Linkml: 1.2.11

**Comment by adlerfaulkner** [comment]
Also when attempting to infer the output type as jsonld via:
`linkml-convert -s personinfo.yaml person.yaml -o data.jsonld` 

I get:
```
Traceback (most recent call last):
  File "/Users/adlerfaulkner/skl/venv/bin/linkml-convert", line 8, in <module>
    sys.exit(cli())
  File "/Users/adlerfaulkner/skl/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/adlerfaulkner/skl/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/adlerfaulkner/skl/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/adlerfaulkner/skl/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/adlerfaulkner/skl/venv/lib/python3.9/site-packages/linkml/utils/converter.py", line 134, in cli
    dumper.dump(obj, output, **outargs)
  File "/Users/adlerfaulkner/skl/venv/lib/python3.9/site-packages/linkml_runtime/dumpers/rdflib_dumper.py", line 132, in dump
    super().dump(element, to_file, schemaview=schemaview, fmt=fmt, prefix_map=prefix_map)
  File "/Users/adlerfaulkner/skl/venv/lib/python3.9/site-packages/linkml_runtime/dumpers/dumper_root.py", line 17, in dump
    output_file.write(self.dumps(element, **_))
  File "/Users/adlerfaulkner/skl/venv/lib/python3.9/site-packages/linkml_runtime/dumpers/rdflib_dumper.py", line 145, in dumps
    return self.as_rdf_graph(element, schemaview, prefix_map=prefix_map).\
  File "/Users/adlerfaulkner/skl/venv/lib/python3.9/site-packages/linkml_runtime/dumpers/rdflib_dumper.py", line 40, in as_rdf_graph
    self.inject_triples(element, schemaview, g)
  File "/Users/adlerfaulkner/skl/venv/lib/python3.9/site-packages/linkml_runtime/dumpers/rdflib_dumper.py", line 53, in inject_triples
    namespaces = schemaview.namespaces()
AttributeError: 'NoneType' object has no attribute 'namespaces'
```

**Comment by adlerfaulkner** [comment]
Looks like the `json-ld` case here in [datautils.py](https://github.com/linkml/linkml/blob/009766b4fc2a2d877d8ed2750046cc43b9ea031b/linkml/utils/datautils.py#L28) should be using `RDFDumper` rather than `RDFLibDumper`. 

[`RDFDumper#dump`](https://github.com/linkml/linkml-runtime/blob/main/linkml_runtime/dumpers/rdf_dumper.py#L66) supports a `contexts` argument while [`RDFLibDumper#dump`](https://github.com/linkml/linkml-runtime/blob/main/linkml_runtime/dumpers/rdflib_dumper.py#L118) does not.

```
dumpers_loaders = {
    'yaml': (YAMLDumper, YAMLLoader),
    'json': (JSONDumper, JSONLoader),
    'rdf': (RDFLibDumper, RDFLibLoader),
    'ttl': (RDFLibDumper, RDFLibLoader),
    'json-ld': (RDFLibDumper, RDFLibLoader),
    'csv': (CSVDumper, CSVLoader),
    'tsv': (CSVDumper, CSVLoader),
}
```

**Comment by cmungall** [comment]
Thanks for the report and the analysis - very useful.

In theory generating jsonld from the rdflib dumper should work - however, the jsonld will be unframed which may be counter to expectations.

We should fix things such that rdf_dumper is used for jsonld exports by default (as this uses the route of standard json export + separate json-ld context export), although we should also check why going via rdflib to create a direct rdf model and then serializing as jsonld does not work.

We also need to improve our documentation here a little:

https://linkml.io/linkml/developers/loaders-and-dumpers.html

**Comment by matentzn** [comment]
Not sure if it is the same issue. Running:

```
linkml-convert -t rdf -s omop.yaml -S person_list -C Person person.tsv
```

Results in:

```
Traceback (most recent call last):
  File "/Users/matentzn/opt/anaconda3/bin/linkml-convert", line 8, in <module>
    sys.exit(cli())
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/linkml/utils/converter.py", line 111, in cli
    obj = loader.load(source=input,  target_class=py_target_class, **inargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/linkml_runtime/loaders/csv_loader.py", line 40, in load
    configmap = get_configmap(schemaview, index_slot)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/linkml_runtime/utils/csvutils.py", line 19, in get_configmap
    if slot.range is not None and slot.range in schemaview.all_classes():
AttributeError: 'NoneType' object has no attribute 'range'
```

Reproducible example here:
https://github.com/matentzn/omop-linkml/blob/master/Makefile#L8

Not sure how to debug this.

**Comment by cmungall** [comment]
I think any issue you are having is entirely separate. The rdflib based translation is complete as far as we are aware. And you aren't even reaching that point, your command is failing at the TSV parsing stage

**Comment by sierra-moxon** [comment]
closing as complete per last message, please reopen if I have this wrong.
