### ISSUE TITLE
Linkml runtime does not recognise class for `linkml-convert`

### ISSUE THREAD

**Issue by matentzn** [linkml/linkml#809]
```
 pip list | grep linkm
linkml                             1.2.12
linkml-dataops                     0.1.0
linkml-model                       1.2.0
linkml-runtime                     1.2.15
```

Running a convert (after using schema enrichment toolkit):

```
linkml-convert -t rdf -s target/omop_concepts.yaml -S concept_id_1 -C CONCEPT_RELATIONSHIP local/CONCEPT_RELATIONSHIP_HEAD.csv
Traceback (most recent call last):
  File "/Users/matentzn/opt/anaconda3/bin/linkml-convert", line 8, in <module>
    sys.exit(cli())
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/linkml/utils/converter.py", line 93, in cli
    py_target_class = python_module.__dict__[target_class]
KeyError: 'CONCEPT_RELATIONSHIP'
make: *** [target/omop_relationship.ttl] Error 1
```

Just for funzy, when trying the same without `-C`:

```
matentzn@mbp.local:~/ws/schema-automator (main) $ linkml-convert -t rdf -s target/omop_concepts.yaml -S concept_id_1  local/CONCEPT_RELATIONSHIP_HEAD.csv
Traceback (most recent call last):
  File "/Users/matentzn/opt/anaconda3/bin/linkml-convert", line 8, in <module>
    sys.exit(cli())
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/linkml/utils/converter.py", line 90, in cli
    target_class = infer_root_class(sv)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/linkml/utils/datautils.py", line 95, in infer_root_class
    raise RuntimeError(f"Multiple potential target classes found: {candidates}. "
RuntimeError: Multiple potential target classes found: ['CONCEPT_RELATIONSHIP', 'CONCEPT_ANCESTOR', 'CONCEPT_CLASS', 'CONCEPT_SYNONYM', 'CONCEPT', 'DOMAIN', 'RELATIONSHIP', 'VOCABULARY']. Please specify a target using --target_class or by adding tree_root: true to the relevant class in the schema.
```

Any idea what I am doing wrong? The generated LinkML schema looks fine to my innocent eyes.

**Comment by cmungall** [comment]
hard to say without seeing the yaml

In general it's good to declare a tree_root explicitly, assuming this is uniform for all exports

https://linkml.io/linkml/data/csvs.html?highlight=tree_root#container-objects

You can then leave off `-C`, and the second route should work

But the first route should work. I suspect there is something happening with canonicalizing class names. The `-C` should take the canonical python name of the class. This obviously needs better documented and more informative errors reported.

**Comment by matentzn** [comment]
Ok, indeed, this issue is solved when using the canonical Python name. 

FWIW, I would prefer we restrict the permissible lexical representation of the class name in linkml to whatever the Python name will become, but I know this is not going to happen - just wanted to mention this.

Issue can be closed unless you want to use it as a prompt for updating the documentations (we need something like a typical error page, or even better, the exception should be caught and something useful should be told to the user of where to look.
