### ISSUE TITLE
linkml-sqldb dump from TSV can't handle strings longer than 131072 characters

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#815]
In the Celniker FELIX database (for the Synbio Ontology project), most of the nucleic acid sequences are shorter than 50k nt. But there is one 202,036 nt long sequence and I would like to add that to a SQLite database with LinkML validation.

```
Traceback (most recent call last):
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/linkml-project-template-d6UeGt0V-py3.9/bin/linkml-sqldb", line 8, in <module>
    sys.exit(main())
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/linkml-project-template-d6UeGt0V-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/linkml-project-template-d6UeGt0V-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/linkml-project-template-d6UeGt0V-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/linkml-project-template-d6UeGt0V-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/linkml-project-template-d6UeGt0V-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/linkml-project-template-d6UeGt0V-py3.9/lib/python3.9/site-packages/linkml/utils/sqlutils.py", line 325, in dump
    obj = loader.load(source=input,  target_class=py_target_class, **inargs)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/linkml-project-template-d6UeGt0V-py3.9/lib/python3.9/site-packages/linkml_runtime/loaders/csv_loader.py", line 43, in load
    objs = unflatten_from_csv(source, config=config, **kwargs)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/linkml-project-template-d6UeGt0V-py3.9/lib/python3.9/site-packages/json_flattener/flattener.py", line 351, in unflatten_from_csv
    for row in r:
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/csv.py", line 111, in __next__
    row = next(self.reader)
_csv.Error: field larger than field limit (131072)
```

**Comment by cmungall** [comment]
Looks like a csv issue not a linkml one:

Does this help? https://stackoverflow.com/questions/15063936/csv-error-field-larger-than-field-limit-131072

It may be awkward to pass this through though - especially as this is within the external json_flattern lib (which I wrote)

- env vars - yuck
- try/except increasing the limit by 10* each time?
- adding a limit to the signature - awkward as this will need passed down from CLI to csv_loader to json_flattener to csv...

of course for now you can simply write a short python loader that is specific to this csv file, or some kind of generic csv to yaml, a little unsatisfying...

**Comment by turbomam** [comment]
Thanks, @cmungall! I can confirm that long strings in YAML work with `linkml-sqldb dump`, but [the same longs strings from TSV don't.](https://github.com/linkml/linkml/pull/822)

It's an edge case for Susans data at this point, so I'm willing to close the issue and revisit in the future.
