### ISSUE TITLE
._normalize_inlined_as_list does not work for enum slots

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#817]
See also #811.  

```yaml
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
imports:
  - linkml:types
prefixes:
  personinfo: https://w3id.org/linkml/examples/personinfo/
  linkml: https://w3id.org/linkml/
default_prefix: personinfo
default_range: string

emit_prefixes:
  - rdf
  - rdfs
  - xsd
  - skos

classes:


  Person:
    slots:
      - id
      - name
      - vital_status
  PersonNoId:
    slots:
      - name
      - vital_status
  Container:
    tree_root: true
    slots:
      - name
      - persons_as_list
      - persons_as_dict
      - single_person_inlined
      - noidobj_as_list
      - noidobj_as_dict
      - single_noidobj_inlined

slots:
  id:
    identifier: true
  name: {}

  persons_as_list:
    range: Person
    inlined: true
    inlined_as_list: true
    multivalued: true
  persons_as_dict:
    range: Person
    inlined: true
    inlined_as_list: false
    multivalued: true
  single_person_inlined:
    inlined: true
    range: Person

  noidobj_as_list:
    range: Person
    inlined: true
    inlined_as_list: true
    multivalued: true
  noidobj_as_dict:
    range: Person
    inlined: true
    inlined_as_list: false
    multivalued: true
  single_noidobj_inlined:
    inlined: true
    range: Person

  vital_status:
    range: VitalStatusEnum

enums:
  VitalStatusEnum:
    permissible_values:
      LIVING:
      DEAD:
```

For both persons_as_list and persons_as_dict, _normalize_inlined_as_list and _normalize_inlined_as_dict are generated in the dataclass python

e.g.

```python
     self._normalize_inlined_as_list(slot_name="persons_as_list",  slot_type=Person, key_name="id", keyed=True)
```

When creating objects via nested constructors an error will be thrown when instantiating the enum object - instead its necessary to set these fields post object creation

error:

```
Traceback (most recent call last):
  File "/home/runner/work/linkml/linkml/tests/test_issues/test_linkml_issue_817.py", line 47, in test_inline
    c = mod.Container(persons_as_list=[p], persons_as_dict=[p])
  File "<string>", line 10, in __init__
  File "test", line 121, in __post_init__
  File "/home/runner/work/linkml/linkml/.venv/lib/python3.10/site-packages/linkml_runtime/utils/yamlutils.py", line 97, in _normalize_inlined_as_list
    self._normalize_inlined(slot_name, slot_type, key_name, keyed, True)
  File "/home/runner/work/linkml/linkml/.venv/lib/python3.10/site-packages/linkml_runtime/utils/yamlutils.py", line 180, in _normalize_inlined
    cooked_obj = slot_type(**as_dict(list_entry))
  File "<string>", line 6, in __init__
  File "test", line 73, in __post_init__
  File "/home/runner/work/linkml/linkml/.venv/lib/python3.10/site-packages/linkml_runtime/utils/enumerations.py", line 46, in __init__
    if key not in self.__class__ and self._defn.code_set:
  File "/home/runner/work/linkml/linkml/.venv/lib/python3.10/site-packages/linkml_runtime/utils/enumerations.py", line 28, in __contains__
    return item in cls.__dict__
TypeError: unhashable type: 'JsonObj'
```

In:

https://github.com/linkml/linkml-runtime/blob/444c6a8d1ed70d012d92671f6e3cbd0797a39a03/linkml_runtime/utils/yamlutils.py#L180

The passed dictionary looks like this:

```
{'id': 'x', 'name': 'x', 'vital_status': {'_code': {'text': 'LIVING', 'description': None, 'meaning': None, 'is_a': None, ...
```

This is something to do with how enums are stored as JsonObjs

note this only occurs if the parent object has an indentifier; in the above example `noidobj_as_list` works

**Comment by cmungall** [comment]
Related: #265 
This fix: https://github.com/linkml/linkml/commit/92a41f114af141e525f42dc30434f42c89d0a455
