### ISSUE TITLE
add mode for prioritizing brief error message over stack traces

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#892]
for example, in `linkml-validate`

**Comment by turbomam** [comment]
From Quan Wan from the Curated Metagenomic Data

**Comment by QuanWan89** [comment]
If I use command line to validate data, it will print traceback information.
`linkml-validate -s personinfo.yaml data.yaml`

Output:
`Traceback (most recent call last):
  File "/Users/cui/opt/anaconda3/bin/linkml-validate", line 8, in <module>
    sys.exit(cli())
  File "/Users/cui/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cui/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/cui/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cui/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/cui/opt/anaconda3/lib/python3.9/site-packages/linkml/validators/jsonschemavalidator.py", line 99, in cli
    obj = loader.load(source=input,  target_class=py_target_class, **inargs)
  File "/Users/cui/opt/anaconda3/lib/python3.9/site-packages/linkml_runtime/loaders/loader_root.py", line 85, in load
    results = self.load_any(*args, **kwargs)
  File "/Users/cui/opt/anaconda3/lib/python3.9/site-packages/linkml_runtime/loaders/yaml_loader.py", line 25, in load_any
    return self.load_source(source, loader, target_class, accept_header="text/yaml, application/yaml;q=0.9",
  File "/Users/cui/opt/anaconda3/lib/python3.9/site-packages/linkml_runtime/loaders/loader_root.py", line 66, in load_source
    return target_class(**data_as_dict)
  File "<string>", line 4, in __init__
  File "test", line 98, in __post_init__
  File "/Users/cui/opt/anaconda3/lib/python3.9/site-packages/linkml_runtime/utils/yamlutils.py", line 97, in _normalize_inlined_as_list
    self._normalize_inlined(slot_name, slot_type, key_name, keyed, True)
  File "/Users/cui/opt/anaconda3/lib/python3.9/site-packages/linkml_runtime/utils/yamlutils.py", line 182, in _normalize_inlined
    cooked_obj = slot_type(**as_dict(list_entry))
  File "<string>", line 8, in __init__
  File "test", line 67, in __post_init__
  File "/Users/cui/opt/anaconda3/lib/python3.9/site-packages/linkml_runtime/utils/yamlutils.py", line 250, in MissingRequiredField
    raise ValueError(f"{field_name} must be supplied")
ValueError: full_name must be supplied`

Do we consider to separate different mode? For example, for general users, linkml returns formatted checking results. For developers, we return traceback info within debug or verbose mode. Thanks.

**Comment by sierra-moxon** [comment]
Thanks for the idea @QuanWan89 and @turbomam - can you give me an idea of the non-developer use case?  Also, it would be very helpful to see an example of the kind of non-developer error message that would be helpful for your users.  :)

**Comment by QuanWan89** [comment]
@sierra-moxon Thanks for you reply. I think for non-developer we should just return human-readable checking error, which means the last line of current output without traceback information. @turbomam How do you feel about it?

**Comment by cmungall** [comment]
See also https://github.com/linkml/linkml/issues/368

**Comment by nlharris** [comment]
Related to #588?

**Comment by cmungall** [comment]
Replacing this one with the newer

- #1039
