### ISSUE TITLE
Incorrect order of required and optional properties in autogenerated Python dataclasses

### ISSUE THREAD

**Issue by deepakunni3** [linkml/linkml#93]
This bug was discovered in Biolink Model where when we have required and optional properties, somehow the order in which these are declared in the autogenerated Python dataclass is incorrect, which leads to the following stacktrace:
```sh
pipenv run gen-py-classes biolink-model.yaml > biolink/model.py.tmp && pipenv run python biolink/model.py.tmp &&  mv biolink/model.py.tmp biolink/model.py
/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/biolinkml/__init__.py:158: UserWarning: Some URL processing will fail with python 3.7.5 or earlier.  Current version: sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
  warn(f"Some URL processing will fail with python 3.7.5 or earlier.  Current version: {sys.version_info}")
/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/biolinkml/__init__.py:158: UserWarning: Some URL processing will fail with python 3.7.5 or earlier.  Current version: sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
  warn(f"Some URL processing will fail with python 3.7.5 or earlier.  Current version: {sys.version_info}")
Traceback (most recent call last):
  File "biolink/model.py.tmp", line 1098, in <module>
    class NamedThing(YAMLRoot):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 991, in dataclass
    return wrap(_cls)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 983, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 904, in _process_class
    else 'self',
  File "/Users/deepak.unni3/.local/share/virtualenvs/biolink-model-master-5d11vXBI/lib/python3.7/site-packages/biolinkml/utils/dataclass_extensions_375.py", line 19, in dataclasses_init_fn_with_kwargs
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'name' follows default argument
make: *** [biolink/model.py] Error 1
```

This bug can be reproduced on biolinkml 1.6.0 and the following version of biolink model YAML: https://github.com/biolink/biolink-model/blob/4fe5cb12c5a7af5fbc20fc94286528ccc35ad6ce/biolink-model.yaml

**Comment by cmungall** [comment]
@sujaypatil96 can you check if this is still an issue and close if not? Seems like this would be a serious blocker for biolink if it were still an issue, cc @sierra-moxon

**Comment by cmungall** [comment]
I assume this is fixed
