### ISSUE TITLE
linkml-lint command fails when config file can't be located

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#952]
If the `linkml-lint` command is run without passing the `--config` parameter _and_ there is no implicit config file (`.linkmllint.yaml` in the current working directory) the command fails with:

```
Traceback (most recent call last):
  File ".../linkml/.venv/bin/linkml-lint", line 5, in <module>
    main()
  File ".../linkml/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File ".../linkml/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File ".../linkml/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../linkml/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File ".../linkml/linkml/linter/cli.py", line 65, in main
    linter = Linter(config_dict)
  File ".../linkml/linkml/linter/linter.py", line 45, in __init__
    merged_config = merge_configs(default_config, config)
  File ".../linkml/linkml/linter/linter.py", line 34, in merge_configs
    for key, value in other.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by pkalita-lbl** [comment]
Ah, I made a duplicate! Thanks for pointing that out.
