### ISSUE TITLE
Update linkml-project-cookiecutter README to include poetry virtual env setup so that cruft is not installed globally. 

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#963]
I can not get this to work, even from a clean poetry virtual shell without specifying that click stay pinned at 8.0.4.  
here's my recipe: 
python 3.9.7 installed via pyenv
```
% mkdir cookies
% cd cookies
% poetry init
% add cruft as a dependency (use the latest version by default)
% poetry install
% poetry show # click gets installed by cruft with 8.1.3, typer gets installed at 0.6.1
% poetry shell
% cruft create https://github.com/linkml/linkml-project-cookiecutter # use defaults for everything
github_token_for_pypi_deployment [PYPI_PASSWORD (leave blank if not a python project)]: 
  File "/var/folders/2d/1xhwsfs15qb37bv4m62xn0tc0000gp/T/tmp3nm58nwv.py", line 10
    project_slug = '{{ cookiecutter.project_name|lower()|replace(' ', '_')|replace('-', '_') }}'
                                                                       ^
SyntaxError: invalid syntax
Stopping generation because post_gen_project hook script didn't exit successfully
Traceback (most recent call last):
  File "/usr/local/bin/cruft", line 8, in <module>
    sys.exit(app())
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/cruft/_cli.py", line 104, in create
    _commands.create(
  File "/usr/local/lib/python3.9/site-packages/cruft/_commands/utils/__init__.py", line 14, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cruft/_commands/create.py", line 45, in create
    generate_files(
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/generate.py", line 361, in generate_files
    _run_hook_from_repo_dir(
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/generate.py", line 237, in _run_hook_from_repo_dir
    run_hook(hook_name, project_dir, context)
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/hooks.py", line 131, in run_hook
    run_script_with_context(script, project_dir, context)
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/hooks.py", line 115, in run_script_with_context
    run_script(temp.name, cwd)
  File "/usr/local/lib/python3.9/site-packages/cookiecutter/hooks.py", line 86, in run_script
    raise FailedHookException(
cookiecutter.exceptions.FailedHookException: Hook script failed (exit status: 1)
```

Alternatively, this recipe works:
```
% mkdir cookies
% cd cookies
% poetry init
% add click as a dependency (pin to 8.0.4)
% add cruft as a dependency (use the latest version by default)
% poetry install
% poetry show # click gets installed by cruft with 8.0.4, typer gets installed at 0.6.1
% poetry shell
% cruft create https://github.com/linkml/linkml-project-cookiecutter # use defaults for everything

** PROJECT CREATION COMPLETE **

Next steps:
cd my-awesome-schema
make setup
```

It would be cool if someone else could try my recipe and see if it works for them?

**Comment by sierra-moxon** [comment]
done.
